-- ============================================================
-- 数据库智能平台 - Oracle平台库初始化脚本
-- 执行用户: moitor
-- Oracle版本: 19c
-- ============================================================

-- 1. 用户表
CREATE TABLE SYS_USER (
  USER_ID       NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  USERNAME      VARCHAR2(64)  NOT NULL UNIQUE,
  PASSWORD_HASH VARCHAR2(128) NOT NULL,
  REAL_NAME     VARCHAR2(64),
  EMAIL         VARCHAR2(128),
  PHONE         VARCHAR2(32),
  ROLE          VARCHAR2(32)  DEFAULT 'VIEWER' NOT NULL,  -- ADMIN/DBA/OPS/REVIEWER/VIEWER/DEV
  STATUS        NUMBER(1)     DEFAULT 1 NOT NULL,          -- 1:启用 0:禁用
  TENANT_ID     NUMBER        DEFAULT 1,
  LAST_LOGIN    TIMESTAMP,
  PWD_CHANGED   TIMESTAMP,
  CREATED_AT    TIMESTAMP     DEFAULT SYSTIMESTAMP,
  UPDATED_AT    TIMESTAMP     DEFAULT SYSTIMESTAMP
);

COMMENT ON TABLE  SYS_USER IS '平台用户表';
COMMENT ON COLUMN SYS_USER.ROLE IS 'ADMIN超管/DBA数据库管理员/OPS运维工程师/REVIEWER审核员/VIEWER只读/DEV开发';

-- 1b. RBAC：角色、菜单、角色-菜单（SYS_USER.ROLE 与 SYS_ROLE.ROLE_CODE 对应；增量升级见 migration_v1_5_rbac.sql）
CREATE TABLE SYS_ROLE (
  ROLE_ID       NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  ROLE_CODE     VARCHAR2(32)  NOT NULL UNIQUE,
  ROLE_NAME     VARCHAR2(64)  NOT NULL,
  STATUS        NUMBER(1)     DEFAULT 1 NOT NULL,
  IS_SYSTEM     NUMBER(1)     DEFAULT 0 NOT NULL,
  SORT_ORDER    NUMBER        DEFAULT 0,
  CREATED_AT    TIMESTAMP     DEFAULT SYSTIMESTAMP,
  UPDATED_AT    TIMESTAMP     DEFAULT SYSTIMESTAMP
);

COMMENT ON TABLE SYS_ROLE IS '系统角色';
COMMENT ON COLUMN SYS_ROLE.IS_SYSTEM IS '1=内置角色，禁止删除';

CREATE TABLE SYS_MENU (
  MENU_ID       NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  MENU_PATH     VARCHAR2(256) NOT NULL UNIQUE,
  MENU_NAME     VARCHAR2(64)  NOT NULL,
  PARENT_PATH   VARCHAR2(256),
  ICON          VARCHAR2(64),
  SORT_ORDER    NUMBER        DEFAULT 0,
  CREATED_AT    TIMESTAMP     DEFAULT SYSTIMESTAMP
);

COMMENT ON TABLE SYS_MENU IS '侧栏菜单（路径与前端路由一致）';

CREATE TABLE SYS_ROLE_MENU (
  ROLE_ID       NUMBER NOT NULL,
  MENU_ID       NUMBER NOT NULL,
  CONSTRAINT PK_SYS_ROLE_MENU PRIMARY KEY (ROLE_ID, MENU_ID),
  CONSTRAINT FK_SRM_ROLE FOREIGN KEY (ROLE_ID) REFERENCES SYS_ROLE(ROLE_ID) ON DELETE CASCADE,
  CONSTRAINT FK_SRM_MENU FOREIGN KEY (MENU_ID) REFERENCES SYS_MENU(MENU_ID) ON DELETE CASCADE
);

COMMENT ON TABLE SYS_ROLE_MENU IS '角色可访问菜单';

-- 2. 审计日志表（按月分区）
CREATE TABLE SYS_AUDIT_LOG (
  LOG_ID       NUMBER GENERATED ALWAYS AS IDENTITY,
  USER_ID      NUMBER,
  USERNAME     VARCHAR2(64),
  ACTION       VARCHAR2(128),
  "RESOURCE"    VARCHAR2(128),
  RESOURCE_ID  VARCHAR2(64),
  IP_ADDR      VARCHAR2(64),
  STATUS       VARCHAR2(16),  -- SUCCESS/FAIL
  DETAIL       CLOB,
  CREATED_AT   TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL
) PARTITION BY RANGE (CREATED_AT) INTERVAL (NUMTOYMINTERVAL(1,'MONTH'))
(PARTITION P_INIT VALUES LESS THAN (TIMESTAMP '2026-01-01 00:00:00'));

COMMENT ON TABLE SYS_AUDIT_LOG IS '操作审计日志（不可删除）';

-- 3. 被管数据库实例表
CREATE TABLE CMDB_INSTANCE (
  INSTANCE_ID   NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  INSTANCE_NAME VARCHAR2(128) NOT NULL,
  DB_TYPE       VARCHAR2(32)  NOT NULL,  -- ORACLE/MYSQL/POSTGRESQL
  DB_VERSION    VARCHAR2(64),
  HOST_IP       VARCHAR2(64)  NOT NULL,
  PORT          NUMBER        DEFAULT 1521,
  SERVICE_NAME  VARCHAR2(128),
  SID           VARCHAR2(64),
  DB_USER       VARCHAR2(64),
  DB_PASSWORD   VARCHAR2(256), -- AES加密存储
  CHARSET       VARCHAR2(32),
  STATUS        VARCHAR2(16)  DEFAULT 'RUNNING',  -- RUNNING/STOPPED/ERROR/UNKNOWN
  HEALTH_SCORE  NUMBER(3)     DEFAULT 100,
  ENVIRONMENT   VARCHAR2(32)  DEFAULT 'PROD',  -- PROD/UAT/DEV/TEST
  BIZ_LINE      VARCHAR2(64),
  TAGS          VARCHAR2(256),
  ROLE          VARCHAR2(32)  DEFAULT 'PRIMARY',  -- PRIMARY/STANDBY/READONLY
  CLUSTER_NAME  VARCHAR2(128),
  HOST_ID       NUMBER,
  TENANT_ID     NUMBER        DEFAULT 1,
  CREATED_BY    NUMBER,
  CREATED_AT    TIMESTAMP     DEFAULT SYSTIMESTAMP,
  UPDATED_AT    TIMESTAMP     DEFAULT SYSTIMESTAMP,
  LAST_CHECK    TIMESTAMP
);

COMMENT ON TABLE  CMDB_INSTANCE IS '被管数据库实例';
COMMENT ON COLUMN CMDB_INSTANCE.STATUS IS 'RUNNING运行中/STOPPED已停止/ERROR异常/UNKNOWN未知';

-- 3b. 监控周期采集样本（真实连通后指标入库，供趋势图与 CMDB 健康分）
CREATE TABLE MONITOR_METRIC_SAMPLE (
  SAMPLE_ID     NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  INSTANCE_ID   NUMBER        NOT NULL,
  COLLECTED_AT  TIMESTAMP     DEFAULT SYSTIMESTAMP NOT NULL,
  DB_TYPE       VARCHAR2(32),
  REACHABLE     NUMBER(1)     DEFAULT 1 NOT NULL,
  HEALTH_SCORE  NUMBER(3),
  METRIC_CPU    NUMBER,
  METRIC_CONN   NUMBER,
  METRICS_JSON  CLOB,
  ERR_MSG       VARCHAR2(512)
);

COMMENT ON TABLE MONITOR_METRIC_SAMPLE IS '被管库周期/即时采集快照（JSON + 归一化 CPU/连接度量能）';
CREATE INDEX IDX_MON_SAMPLE_INST_TIME ON MONITOR_METRIC_SAMPLE(INSTANCE_ID, COLLECTED_AT DESC);

-- 4. 主机表
CREATE TABLE CMDB_HOST (
  HOST_ID      NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  HOSTNAME     VARCHAR2(128) NOT NULL,
  IP_ADDR      VARCHAR2(64)  NOT NULL,
  OS_TYPE      VARCHAR2(64),
  OS_VERSION   VARCHAR2(64),
  CPU_CORES    NUMBER,
  MEMORY_GB    NUMBER,
  DATACENTER   VARCHAR2(64),
  STATUS       VARCHAR2(16)  DEFAULT 'ONLINE',
  TENANT_ID    NUMBER        DEFAULT 1,
  CREATED_AT   TIMESTAMP     DEFAULT SYSTIMESTAMP
);

-- 5. 告警规则表
CREATE TABLE ALERT_RULE (
  RULE_ID      NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  RULE_NAME    VARCHAR2(128) NOT NULL,
  RULE_TYPE    VARCHAR2(32)  DEFAULT 'THRESHOLD',  -- THRESHOLD/DYNAMIC/PROMQL
  METRIC       VARCHAR2(128) NOT NULL,
  OPERATOR     VARCHAR2(16),   -- gt/lt/gte/lte/eq
  THRESHOLD    NUMBER,
  DURATION     NUMBER         DEFAULT 5,   -- 分钟
  SEVERITY     VARCHAR2(16)   DEFAULT 'P3', -- P1/P2/P3/P4
  DB_TYPE      VARCHAR2(32),   -- 适用数据库类型，NULL=所有
  INSTANCE_ID  NUMBER,         -- 绑定实例，NULL=所有
  PROMQL       CLOB,
  ENABLED      NUMBER(1)      DEFAULT 1,
  NOTIFY_CHAN  VARCHAR2(256),  -- email,sms,wechat
  NOTIFY_TO    VARCHAR2(512),
  CREATED_BY   NUMBER,
  CREATED_AT   TIMESTAMP      DEFAULT SYSTIMESTAMP
);

-- 6. 告警记录表
CREATE TABLE ALERT_RECORD (
  ALERT_ID     NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  RULE_ID      NUMBER,
  RULE_NAME    VARCHAR2(128),
  INSTANCE_ID  NUMBER,
  INSTANCE_NAME VARCHAR2(128),
  SEVERITY     VARCHAR2(16),
  CONTENT      VARCHAR2(1024),
  STATUS       VARCHAR2(16)  DEFAULT 'OPEN',  -- OPEN/ACKNOWLEDGED/RESOLVED/SUPPRESSED
  TRIGGER_TIME TIMESTAMP     DEFAULT SYSTIMESTAMP,
  ACK_TIME     TIMESTAMP,
  ACK_BY       VARCHAR2(64),
  RESOLVE_TIME TIMESTAMP,
  RESOLVE_BY   VARCHAR2(64),
  DETAIL       CLOB,
  TENANT_ID    NUMBER         DEFAULT 1
);

-- 7. 慢SQL汇总
CREATE TABLE SQL_SLOW_SUMMARY (
  SQL_ID       NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  INSTANCE_ID  NUMBER,
  SQL_TEXT     CLOB,
  SQL_HASH     VARCHAR2(64),
  DB_TYPE      VARCHAR2(32),
  AVG_ELAPSED  NUMBER,   -- 毫秒
  MAX_ELAPSED  NUMBER,
  EXEC_COUNT   NUMBER,
  TOTAL_ELAPSED NUMBER,
  FULL_SCAN    NUMBER(1) DEFAULT 0,
  CAPTURE_TIME TIMESTAMP DEFAULT SYSTIMESTAMP,
  PLAN_HASH    VARCHAR2(64)
);

-- 7b. SQL 优化历史（记录优化建议及执行跟踪）
CREATE TABLE SQL_OPT_HISTORY (
  OPT_ID          NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  SQL_HASH        VARCHAR2(64),
  SQL_TEXT        CLOB NOT NULL,
  DB_TYPE         VARCHAR2(16),
  OPTIMIZED_SQL   CLOB,
  RULE_ENGINE     CLOB,
  EXPLAIN_BEFORE  CLOB,
  EXPLAIN_AFTER   CLOB,
  LLM_PROVIDER    VARCHAR2(32),
  LLM_MODEL       VARCHAR2(128),
  STATUS          VARCHAR2(16) DEFAULT 'PENDING',
  EFFECT_SCORE    NUMBER,
  EFFECT_NOTE     VARCHAR2(1024),
  EXECUTED_AT     TIMESTAMP,
  CREATED_AT      TIMESTAMP DEFAULT SYSTIMESTAMP,
  CREATED_BY      NUMBER
);

COMMENT ON TABLE  SQL_OPT_HISTORY IS 'SQL 优化建议执行跟踪';
COMMENT ON COLUMN SQL_OPT_HISTORY.STATUS IS 'PENDING待处理/ADOPTED已采纳/REJECTED未采纳/EXECUTED已执行';
COMMENT ON COLUMN SQL_OPT_HISTORY.EFFECT_SCORE IS '效果评分 1-5';

-- 8. 巡检结果（BATCH_ID 关联 §5.7 批量巡检任务）
CREATE TABLE INSPECT_RESULT (
  RESULT_ID    NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  INSTANCE_ID  NUMBER,
  BATCH_ID     NUMBER,
  CHECK_ITEM   VARCHAR2(128),
  STATUS       VARCHAR2(16),  -- PASS/WARN/FAIL
  SCORE        NUMBER(3),
  DETAIL       VARCHAR2(1024),
  CHECK_TIME   TIMESTAMP     DEFAULT SYSTIMESTAMP
);

-- 9. 备份策略
CREATE TABLE BACKUP_POLICY (
  POLICY_ID    NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  INSTANCE_ID  NUMBER,
  POLICY_NAME  VARCHAR2(128),
  BACKUP_TYPE  VARCHAR2(32),  -- FULL/INCREMENTAL/ARCHIVE
  SCHEDULE     VARCHAR2(64),   -- cron表达式
  RETENTION    NUMBER DEFAULT 30,  -- 保留天数
  ENABLED      NUMBER(1) DEFAULT 1,
  CREATED_AT   TIMESTAMP DEFAULT SYSTIMESTAMP
);

-- 10. 备份记录
CREATE TABLE BACKUP_RECORD (
  RECORD_ID    NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  POLICY_ID    NUMBER,
  INSTANCE_ID  NUMBER,
  BACKUP_TYPE  VARCHAR2(32),
  STATUS       VARCHAR2(16),  -- RUNNING/SUCCESS/FAILED
  START_TIME   TIMESTAMP,
  END_TIME     TIMESTAMP,
  FILE_PATH    VARCHAR2(512),
  FILE_SIZE    NUMBER,
  DETAIL       VARCHAR2(1024)
);

-- 11～ §5.7 自动化运维（策略与执行落平台库）
CREATE TABLE DEPLOY_TEMPLATE (
  TEMPLATE_ID   NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  TEMPLATE_NAME VARCHAR2(128) NOT NULL,
  DEPLOY_MODE   VARCHAR2(32)  NOT NULL,
  DESCRIPTION   VARCHAR2(512),
  PARAM_SCHEMA  CLOB,
  ENABLED       NUMBER(1) DEFAULT 1,
  CREATED_AT    TIMESTAMP DEFAULT SYSTIMESTAMP,
  UPDATED_AT    TIMESTAMP DEFAULT SYSTIMESTAMP
);

CREATE TABLE DEPLOY_JOB (
  JOB_ID       NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  TEMPLATE_ID  NUMBER,
  INSTANCE_ID  NUMBER,
  STATUS       VARCHAR2(32) DEFAULT 'PENDING',
  PARAMS       CLOB,
  LOG_SUMMARY  VARCHAR2(2000),
  CREATED_BY   NUMBER,
  START_TIME   TIMESTAMP,
  END_TIME     TIMESTAMP,
  CREATED_AT   TIMESTAMP DEFAULT SYSTIMESTAMP
);

CREATE TABLE HA_SWITCH_PLAN (
  PLAN_ID              NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  PLAN_NAME            VARCHAR2(128) NOT NULL,
  PRIMARY_INSTANCE_ID  NUMBER,
  STANDBY_INSTANCE_ID  NUMBER,
  EVAL_RESULT          CLOB,
  STATUS               VARCHAR2(32) DEFAULT 'DRAFT',
  CREATED_AT           TIMESTAMP DEFAULT SYSTIMESTAMP
);

CREATE TABLE HA_SWITCH_AUDIT (
  AUDIT_ID      NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  PLAN_ID       NUMBER NOT NULL,
  ACTION_TYPE   VARCHAR2(64) NOT NULL,
  RESULT_STATUS VARCHAR2(32),
  DETAIL        CLOB,
  OPERATED_BY   VARCHAR2(64),
  CREATED_AT    TIMESTAMP DEFAULT SYSTIMESTAMP
);

CREATE TABLE RUNBOOK_DEF (
  RUNBOOK_ID    NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  RUNBOOK_NAME  VARCHAR2(128) NOT NULL,
  VERSION_NUM   NUMBER DEFAULT 1,
  DAG_JSON      CLOB,
  TRIGGER_ALERT NUMBER(1) DEFAULT 0,
  ENABLED       NUMBER(1) DEFAULT 1,
  CREATED_AT    TIMESTAMP DEFAULT SYSTIMESTAMP
);

CREATE TABLE RUNBOOK_EXEC_LOG (
  EXEC_ID       NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  RUNBOOK_ID    NUMBER NOT NULL,
  INSTANCE_ID   NUMBER,
  TRIGGER_TYPE  VARCHAR2(32) DEFAULT 'MANUAL',
  STATUS        VARCHAR2(32) DEFAULT 'PENDING',
  NODE_LOG      CLOB,
  START_TIME    TIMESTAMP,
  END_TIME      TIMESTAMP,
  CREATED_BY    NUMBER,
  CREATED_AT    TIMESTAMP DEFAULT SYSTIMESTAMP
);

CREATE TABLE SELF_HEAL_POLICY (
  POLICY_ID      NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  POLICY_NAME    VARCHAR2(128) NOT NULL,
  INSTANCE_ID    NUMBER,
  RULE_TYPE      VARCHAR2(64),
  CONDITION_JSON CLOB,
  ACTION_MODE    VARCHAR2(32) DEFAULT 'ALERT_ONLY',
  ENABLED        NUMBER(1) DEFAULT 1,
  CREATED_AT     TIMESTAMP DEFAULT SYSTIMESTAMP
);

CREATE TABLE OPS_SERVICE_CATALOG (
  CATALOG_ID    NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  SERVICE_NAME  VARCHAR2(128) NOT NULL,
  CATEGORY      VARCHAR2(64),
  DESCRIPTION   VARCHAR2(512),
  NEED_APPROVAL NUMBER(1) DEFAULT 1,
  CREATED_AT    TIMESTAMP DEFAULT SYSTIMESTAMP
);

CREATE TABLE OPS_SERVICE_ORDER (
  ORDER_ID      NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  CATALOG_ID    NUMBER,
  INSTANCE_ID   NUMBER,
  STATUS        VARCHAR2(32) DEFAULT 'OPEN',
  TICKET_REF    VARCHAR2(128),
  REMARK        VARCHAR2(512),
  CREATED_BY    NUMBER,
  CREATED_AT    TIMESTAMP DEFAULT SYSTIMESTAMP
);

CREATE TABLE SPACE_POLICY (
  SPACE_POLICY_ID NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  INSTANCE_ID     NUMBER,
  THRESHOLD_PCT   NUMBER DEFAULT 85,
  CLEAN_TMP       NUMBER(1) DEFAULT 0,
  SCHEDULE_CRON   VARCHAR2(64),
  ENABLED         NUMBER(1) DEFAULT 1,
  CREATED_AT      TIMESTAMP DEFAULT SYSTIMESTAMP
);

CREATE TABLE SCRIPT_REPO (
  SCRIPT_ID       NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  SCRIPT_NAME     VARCHAR2(128) NOT NULL,
  LANG            VARCHAR2(16) DEFAULT 'SHELL',
  CONTENT         CLOB,
  VERSION_NUM     NUMBER DEFAULT 1,
  APPROVAL_STATUS VARCHAR2(32) DEFAULT 'DRAFT',
  CREATED_BY      NUMBER,
  CREATED_AT      TIMESTAMP DEFAULT SYSTIMESTAMP
);

CREATE TABLE SCRIPT_EXEC_LOG (
  EXEC_ID        NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  SCRIPT_ID      NUMBER,
  INSTANCE_ID    NUMBER,
  STATUS         VARCHAR2(32),
  EXIT_CODE      NUMBER,
  OUTPUT_SUMMARY VARCHAR2(2000),
  CREATED_BY     NUMBER,
  CREATED_AT     TIMESTAMP DEFAULT SYSTIMESTAMP
);

CREATE TABLE AUTOMATION_INSPECT_BATCH (
  BATCH_ID     NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  BATCH_NAME   VARCHAR2(128),
  INSTANCE_IDS VARCHAR2(2000),
  CRON_EXPR    VARCHAR2(64),
  STATUS       VARCHAR2(32) DEFAULT 'IDLE',
  LAST_RUN_AT  TIMESTAMP,
  SOURCE_TYPE  VARCHAR2(32) DEFAULT 'MANUAL',
  EXCEL_TARGETS CLOB,
  CREATED_AT   TIMESTAMP DEFAULT SYSTIMESTAMP
);

CREATE TABLE AUTOMATION_EXEC_LOG (
  EXEC_ID    NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  CATEGORY   VARCHAR2(32),
  REF_ID     NUMBER,
  ACTION     VARCHAR2(128),
  STATUS     VARCHAR2(32),
  MESSAGE    VARCHAR2(2000),
  CREATED_BY NUMBER,
  CREATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP
);

-- CheckV8 风格 Oracle 深度巡检完整 JSON（平台内执行，无邮件/无许可证）
CREATE TABLE INSPECT_CHECKV8_REPORT (
  REPORT_ID      NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  INSTANCE_ID    NUMBER,
  BATCH_ID       NUMBER,
  ROW_NUM        NUMBER,
  TARGET_LABEL   VARCHAR2(256),
  OVERALL_SCORE  NUMBER(3),
  OVERALL_STATUS VARCHAR2(16),
  SUMMARY        VARCHAR2(4000),
  PAYLOAD        CLOB,
  DOCX_BLOB      BLOB,
  CREATED_BY     NUMBER,
  CREATED_AT     TIMESTAMP DEFAULT SYSTIMESTAMP
);

COMMENT ON TABLE INSPECT_CHECKV8_REPORT IS 'Oracle CheckV8 巡检报告(JSON)，不含邮件加密';

-- AI 智能分析模块表见 migration_v1_4_ai_analysis.sql

COMMENT ON TABLE DEPLOY_TEMPLATE IS 'F-45 安装部署模板';
COMMENT ON TABLE DEPLOY_JOB IS 'F-45 部署任务';
COMMENT ON TABLE HA_SWITCH_PLAN IS 'F-46 HA 切换方案';
COMMENT ON TABLE HA_SWITCH_AUDIT IS 'F-46 HA 切换审计';
COMMENT ON TABLE RUNBOOK_DEF IS 'F-49 Runbook 定义';
COMMENT ON TABLE RUNBOOK_EXEC_LOG IS 'F-49 Runbook 执行流水';
COMMENT ON TABLE SELF_HEAL_POLICY IS 'F-48 故障自愈策略';
COMMENT ON TABLE OPS_SERVICE_CATALOG IS 'F-50 日常操作服务目录';
COMMENT ON TABLE OPS_SERVICE_ORDER IS 'F-50 服务化工单';
COMMENT ON TABLE SPACE_POLICY IS 'F-51 空间/日志策略';
COMMENT ON TABLE SCRIPT_REPO IS 'F-52 脚本库';
COMMENT ON TABLE SCRIPT_EXEC_LOG IS 'F-52 脚本执行日志';
COMMENT ON TABLE AUTOMATION_INSPECT_BATCH IS 'F-53 自动巡检批次';
COMMENT ON TABLE AUTOMATION_EXEC_LOG IS '自动化统一执行摘要';

-- ============================================================
-- 初始化数据
-- ============================================================

-- RBAC 种子（角色、菜单、默认授权；与 migration_v1_5_rbac.sql 逻辑一致）
INSERT INTO SYS_ROLE (ROLE_CODE, ROLE_NAME, STATUS, IS_SYSTEM, SORT_ORDER) VALUES ('ADMIN', '超级管理员', 1, 1, 1);
INSERT INTO SYS_ROLE (ROLE_CODE, ROLE_NAME, STATUS, IS_SYSTEM, SORT_ORDER) VALUES ('DBA', 'DBA', 1, 1, 2);
INSERT INTO SYS_ROLE (ROLE_CODE, ROLE_NAME, STATUS, IS_SYSTEM, SORT_ORDER) VALUES ('OPS', '运维工程师', 1, 1, 3);
INSERT INTO SYS_ROLE (ROLE_CODE, ROLE_NAME, STATUS, IS_SYSTEM, SORT_ORDER) VALUES ('REVIEWER', '审核员', 1, 1, 4);
INSERT INTO SYS_ROLE (ROLE_CODE, ROLE_NAME, STATUS, IS_SYSTEM, SORT_ORDER) VALUES ('VIEWER', '只读用户', 1, 1, 5);
INSERT INTO SYS_ROLE (ROLE_CODE, ROLE_NAME, STATUS, IS_SYSTEM, SORT_ORDER) VALUES ('DEV', '开发人员', 1, 1, 6);

INSERT INTO SYS_MENU (MENU_PATH, MENU_NAME, SORT_ORDER) VALUES ('/dashboard', '控制台', 10);
INSERT INTO SYS_MENU (MENU_PATH, MENU_NAME, SORT_ORDER) VALUES ('/monitor', '监控中心', 20);
INSERT INTO SYS_MENU (MENU_PATH, MENU_NAME, SORT_ORDER) VALUES ('/monitor/collect-scheduler', '定时采集观测', 30);
INSERT INTO SYS_MENU (MENU_PATH, MENU_NAME, SORT_ORDER) VALUES ('/alerts', '告警中心', 40);
INSERT INTO SYS_MENU (MENU_PATH, MENU_NAME, SORT_ORDER) VALUES ('/cmdb', '资产管理', 50);
INSERT INTO SYS_MENU (MENU_PATH, MENU_NAME, SORT_ORDER) VALUES ('/automation', '自动化运维', 60);
INSERT INTO SYS_MENU (MENU_PATH, MENU_NAME, SORT_ORDER) VALUES ('/sql', 'SQL优化', 70);
INSERT INTO SYS_MENU (MENU_PATH, MENU_NAME, SORT_ORDER) VALUES ('/reports', '报表中心', 80);
INSERT INTO SYS_MENU (MENU_PATH, MENU_NAME, SORT_ORDER) VALUES ('/ai', 'AI 智能分析', 90);
INSERT INTO SYS_MENU (MENU_PATH, MENU_NAME, SORT_ORDER) VALUES ('/settings/profile', '个人设置', 100);
INSERT INTO SYS_MENU (MENU_PATH, MENU_NAME, SORT_ORDER) VALUES ('/settings/users', '用户管理', 110);
INSERT INTO SYS_MENU (MENU_PATH, MENU_NAME, SORT_ORDER) VALUES ('/settings/roles', '角色权限', 120);

INSERT INTO SYS_ROLE_MENU (ROLE_ID, MENU_ID)
SELECT r.ROLE_ID, m.MENU_ID
FROM SYS_ROLE r
CROSS JOIN SYS_MENU m
WHERE r.ROLE_CODE = 'ADMIN';

INSERT INTO SYS_ROLE_MENU (ROLE_ID, MENU_ID)
SELECT r.ROLE_ID, m.MENU_ID
FROM SYS_ROLE r
JOIN SYS_MENU m ON m.MENU_PATH NOT IN ('/settings/users', '/settings/roles')
WHERE r.ROLE_CODE IN ('DBA', 'OPS', 'REVIEWER', 'DEV');

INSERT INTO SYS_ROLE_MENU (ROLE_ID, MENU_ID)
SELECT r.ROLE_ID, m.MENU_ID
FROM SYS_ROLE r
JOIN SYS_MENU m ON m.MENU_PATH IN ('/dashboard', '/monitor', '/monitor/collect-scheduler', '/alerts', '/settings/profile')
WHERE r.ROLE_CODE = 'VIEWER';

-- 若库中已有 admin 但无法登录（旧脚本哈希错误），可单独执行：
-- UPDATE SYS_USER SET PASSWORD_HASH='$2a$10$J2CismMd4XFH7fTycfzoxulfizs6ejZJmoISYocFeDI3NrxrctphO', UPDATED_AT=SYSTIMESTAMP WHERE USERNAME='admin';
-- UPDATE SYS_USER SET PASSWORD_HASH='$2a$10$N5PqPmqn8NtKlKq2pIcoAOjfpmi0/.2/2grhyOhirR/IYCzHPaawa', UPDATED_AT=SYSTIMESTAMP WHERE USERNAME='dba';

-- 默认管理员账号 admin / Admin@123456（bcryptjs 10 rounds，与后端校验一致）
INSERT INTO SYS_USER (USERNAME, PASSWORD_HASH, REAL_NAME, EMAIL, ROLE, STATUS, TENANT_ID)
VALUES ('admin', '$2a$10$J2CismMd4XFH7fTycfzoxulfizs6ejZJmoISYocFeDI3NrxrctphO', '超级管理员', 'admin@dbops.local', 'ADMIN', 1, 1);

-- 默认DBA账号 dba / Dba@123456
INSERT INTO SYS_USER (USERNAME, PASSWORD_HASH, REAL_NAME, EMAIL, ROLE, STATUS, TENANT_ID)
VALUES ('dba', '$2a$10$N5PqPmqn8NtKlKq2pIcoAOjfpmi0/.2/2grhyOhirR/IYCzHPaawa', 'DBA管理员', 'dba@dbops.local', 'DBA', 1, 1);

-- 示例主机
INSERT INTO CMDB_HOST (HOSTNAME, IP_ADDR, OS_TYPE, OS_VERSION, CPU_CORES, MEMORY_GB, DATACENTER)
VALUES ('db-server-01', '192.168.137.102', 'Linux', 'CentOS 7.9', 8, 32, '主机房');

INSERT INTO CMDB_HOST (HOSTNAME, IP_ADDR, OS_TYPE, OS_VERSION, CPU_CORES, MEMORY_GB, DATACENTER)
VALUES ('db-server-02', '192.168.137.103', 'Linux', 'RHEL 8.6', 16, 64, '主机房');

-- 示例被管实例（含平台自身连接的Oracle）
INSERT INTO CMDB_INSTANCE (INSTANCE_NAME, DB_TYPE, DB_VERSION, HOST_IP, PORT, SID, SERVICE_NAME, DB_USER, DB_PASSWORD, CHARSET, STATUS, ENVIRONMENT, BIZ_LINE, HEALTH_SCORE, HOST_ID)
VALUES ('ORA19C-PROD', 'ORACLE', 'Oracle 19c', '192.168.137.102', 1521, 'ora19c', 'ora19c', 'moitor', 'ENCRYPTED:b3JhY2xl', 'AL32UTF8', 'RUNNING', 'PROD', '核心业务', 95, 1);

INSERT INTO CMDB_INSTANCE (INSTANCE_NAME, DB_TYPE, DB_VERSION, HOST_IP, PORT, SID, DB_USER, DB_PASSWORD, CHARSET, STATUS, ENVIRONMENT, BIZ_LINE, HEALTH_SCORE, HOST_ID)
VALUES ('MySQL-UAT', 'MYSQL', 'MySQL 8.0.36', '192.168.137.103', 3306, NULL, 'root', 'ENCRYPTED:cm9vdA==', 'utf8mb4', 'RUNNING', 'UAT', '营销系统', 88, 2);

-- 示例告警规则
INSERT INTO ALERT_RULE (RULE_NAME, METRIC, OPERATOR, THRESHOLD, DURATION, SEVERITY, DB_TYPE, ENABLED)
VALUES ('CPU使用率过高', 'host_cpu_usage', 'gt', 85, 5, 'P2', NULL, 1);

INSERT INTO ALERT_RULE (RULE_NAME, METRIC, OPERATOR, THRESHOLD, DURATION, SEVERITY, DB_TYPE, ENABLED)
VALUES ('表空间使用率告警', 'tablespace_usage_pct', 'gt', 80, 1, 'P2', 'ORACLE', 1);

INSERT INTO ALERT_RULE (RULE_NAME, METRIC, OPERATOR, THRESHOLD, DURATION, SEVERITY, DB_TYPE, ENABLED)
VALUES ('活跃连接数过高', 'db_active_sessions', 'gt', 200, 3, 'P3', 'ORACLE', 1);

INSERT INTO ALERT_RULE (RULE_NAME, METRIC, OPERATOR, THRESHOLD, DURATION, SEVERITY, DB_TYPE, ENABLED)
VALUES ('Buffer Cache命中率过低', 'oracle_buffer_cache_hit', 'lt', 95, 5, 'P3', 'ORACLE', 1);

-- 示例告警记录
INSERT INTO ALERT_RECORD (RULE_ID, RULE_NAME, INSTANCE_ID, INSTANCE_NAME, SEVERITY, CONTENT, STATUS, TRIGGER_TIME)
VALUES (2, '表空间使用率告警', 1, 'ORA19C-PROD', 'P2', 'SYSTEM表空间使用率达到83%，超过告警阈值80%', 'OPEN', SYSTIMESTAMP - 1/24);

INSERT INTO ALERT_RECORD (RULE_ID, RULE_NAME, INSTANCE_ID, INSTANCE_NAME, SEVERITY, CONTENT, STATUS, TRIGGER_TIME, ACK_TIME, ACK_BY)
VALUES (1, 'CPU使用率过高', 1, 'ORA19C-PROD', 'P3', '主机CPU使用率达到91%', 'ACKNOWLEDGED', SYSTIMESTAMP - 3/24, SYSTIMESTAMP - 2/24, 'admin');

-- §5.7 示例数据
INSERT INTO DEPLOY_TEMPLATE (TEMPLATE_NAME, DEPLOY_MODE, DESCRIPTION, PARAM_SCHEMA, ENABLED)
VALUES ('Oracle 单机标准部署', 'SINGLE', '参数化 ORACLE_HOME、SID', '{"sid":"string","oracleHome":"string"}', 1);
INSERT INTO DEPLOY_TEMPLATE (TEMPLATE_NAME, DEPLOY_MODE, DESCRIPTION, ENABLED)
VALUES ('主从复制模板', 'REPLICA', '一主一从', 1);
INSERT INTO RUNBOOK_DEF (RUNBOOK_NAME, VERSION_NUM, DAG_JSON, TRIGGER_ALERT, ENABLED)
VALUES ('表空间告警自愈', 1, '{"nodes":[{"id":"n1","name":"检查表空间"},{"id":"n2","name":"通知DBA"}],"edges":[{"from":"n1","to":"n2"}]}', 1, 1);
INSERT INTO HA_SWITCH_PLAN (PLAN_NAME, PRIMARY_INSTANCE_ID, STANDBY_INSTANCE_ID, STATUS)
VALUES ('ORA19C 生产切换演练', 1, 2, 'DRAFT');
INSERT INTO BACKUP_POLICY (INSTANCE_ID, POLICY_NAME, BACKUP_TYPE, SCHEDULE, RETENTION, ENABLED)
VALUES (1, '每日全备', 'FULL', '0 2 * * *', 30, 1);
INSERT INTO OPS_SERVICE_CATALOG (SERVICE_NAME, CATEGORY, DESCRIPTION, NEED_APPROVAL)
VALUES ('实例扩容申请', 'CAPACITY', 'CPU/内存/存储扩容工单', 1);
INSERT INTO SELF_HEAL_POLICY (POLICY_NAME, INSTANCE_ID, RULE_TYPE, ACTION_MODE, ENABLED)
VALUES ('TEMP 表空间超阈扩容', 1, 'SPACE_EXPAND', 'APPROVAL', 1);
INSERT INTO AUTOMATION_INSPECT_BATCH (BATCH_NAME, INSTANCE_IDS, CRON_EXPR, STATUS)
VALUES ('核心库日检', '1', '0 6 * * *', 'IDLE');

COMMIT;

-- 创建索引
CREATE INDEX IDX_AUDIT_USER ON SYS_AUDIT_LOG(USER_ID, CREATED_AT);
CREATE INDEX IDX_ALERT_INST  ON ALERT_RECORD(INSTANCE_ID, TRIGGER_TIME DESC);
CREATE INDEX IDX_ALERT_STATUS ON ALERT_RECORD(STATUS, SEVERITY);
CREATE INDEX IDX_SQL_INST ON SQL_SLOW_SUMMARY(INSTANCE_ID, CAPTURE_TIME DESC);
CREATE INDEX IDX_INSPECT_BATCH ON INSPECT_RESULT(BATCH_ID);
CREATE INDEX IDX_DEPLOY_JOB_TPL ON DEPLOY_JOB(TEMPLATE_ID);
CREATE INDEX IDX_HA_AUDIT_PLAN ON HA_SWITCH_AUDIT(PLAN_ID);
CREATE INDEX IDX_RB_EXEC_RB ON RUNBOOK_EXEC_LOG(RUNBOOK_ID);
CREATE INDEX IDX_BACKUP_REC_INST ON BACKUP_RECORD(INSTANCE_ID, START_TIME DESC);
CREATE INDEX IDX_CHK8_INST ON INSPECT_CHECKV8_REPORT(INSTANCE_ID, CREATED_AT DESC);
CREATE INDEX IDX_CHK8_BATCH ON INSPECT_CHECKV8_REPORT(BATCH_ID);

COMMIT;
