-- Excel 批量巡检 + Word 报告（在已存在 §5.7 表上增量执行一次）

ALTER TABLE AUTOMATION_INSPECT_BATCH ADD (
  SOURCE_TYPE   VARCHAR2(32) DEFAULT 'MANUAL',
  EXCEL_TARGETS CLOB
);

ALTER TABLE INSPECT_CHECKV8_REPORT MODIFY INSTANCE_ID NULL;
ALTER TABLE INSPECT_CHECKV8_REPORT ADD (
  ROW_NUM      NUMBER,
  TARGET_LABEL VARCHAR2(256),
  DOCX_BLOB    BLOB
);

COMMIT;
