-- F-30 健康评分维度明细
-- MONITOR_METRIC_SAMPLE 新增 HEALTH_DETAIL 列，存储各维度评分 JSON
ALTER TABLE MONITOR_METRIC_SAMPLE ADD HEALTH_DETAIL CLOB;
COMMENT ON COLUMN MONITOR_METRIC_SAMPLE.HEALTH_DETAIL IS '健康评分维度明细JSON（连通性/性能/负载/资源）';
