-- RBAC: 角色、菜单、角色-菜单关联（与 SYS_USER.ROLE 的 ROLE_CODE 对齐）
-- 全新建库：请执行 init.sql（已包含本脚本等价的表结构与种子数据）。
-- 本文件用于「已有库、尚未建 RBAC 表」的增量升级；执行一次即可。若表已存在可跳过 CREATE 段。

-- ========== SYS_ROLE ==========
BEGIN
  EXECUTE IMMEDIATE 'CREATE TABLE SYS_ROLE (
    ROLE_ID       NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    ROLE_CODE     VARCHAR2(32)  NOT NULL UNIQUE,
    ROLE_NAME     VARCHAR2(64)  NOT NULL,
    STATUS        NUMBER(1)     DEFAULT 1 NOT NULL,
    IS_SYSTEM     NUMBER(1)     DEFAULT 0 NOT NULL,
    SORT_ORDER    NUMBER        DEFAULT 0,
    CREATED_AT    TIMESTAMP     DEFAULT SYSTIMESTAMP,
    UPDATED_AT    TIMESTAMP     DEFAULT SYSTIMESTAMP
  )';
EXCEPTION WHEN OTHERS THEN
  IF SQLCODE != -955 THEN RAISE; END IF; -- ORA-00955: name is already used
END;
/

COMMENT ON TABLE SYS_ROLE IS '系统角色';
COMMENT ON COLUMN SYS_ROLE.IS_SYSTEM IS '1=内置角色，禁止删除';

-- ========== SYS_MENU ==========
BEGIN
  EXECUTE IMMEDIATE 'CREATE TABLE SYS_MENU (
    MENU_ID       NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    MENU_PATH     VARCHAR2(256) NOT NULL UNIQUE,
    MENU_NAME     VARCHAR2(64)  NOT NULL,
    PARENT_PATH   VARCHAR2(256),
    ICON          VARCHAR2(64),
    SORT_ORDER    NUMBER        DEFAULT 0,
    CREATED_AT    TIMESTAMP     DEFAULT SYSTIMESTAMP
  )';
EXCEPTION WHEN OTHERS THEN
  IF SQLCODE != -955 THEN RAISE; END IF;
END;
/

COMMENT ON TABLE SYS_MENU IS '侧栏菜单（路径与前端路由一致）';

-- ========== SYS_ROLE_MENU ==========
BEGIN
  EXECUTE IMMEDIATE 'CREATE TABLE SYS_ROLE_MENU (
    ROLE_ID       NUMBER NOT NULL,
    MENU_ID       NUMBER NOT NULL,
    CONSTRAINT PK_SYS_ROLE_MENU PRIMARY KEY (ROLE_ID, MENU_ID),
    CONSTRAINT FK_SRM_ROLE FOREIGN KEY (ROLE_ID) REFERENCES SYS_ROLE(ROLE_ID) ON DELETE CASCADE,
    CONSTRAINT FK_SRM_MENU FOREIGN KEY (MENU_ID) REFERENCES SYS_MENU(MENU_ID) ON DELETE CASCADE
  )';
EXCEPTION WHEN OTHERS THEN
  IF SQLCODE != -955 THEN RAISE; END IF;
END;
/

COMMENT ON TABLE SYS_ROLE_MENU IS '角色可访问菜单';

-- ========== 种子：角色（与现有 SYS_USER.ROLE 枚举一致）==========
MERGE INTO SYS_ROLE t
USING (SELECT 'ADMIN' AS c FROM DUAL) s ON (t.ROLE_CODE = s.c)
WHEN NOT MATCHED THEN INSERT (ROLE_CODE, ROLE_NAME, STATUS, IS_SYSTEM, SORT_ORDER)
  VALUES ('ADMIN', '超级管理员', 1, 1, 1);
MERGE INTO SYS_ROLE t
USING (SELECT 'DBA' AS c FROM DUAL) s ON (t.ROLE_CODE = s.c)
WHEN NOT MATCHED THEN INSERT (ROLE_CODE, ROLE_NAME, STATUS, IS_SYSTEM, SORT_ORDER)
  VALUES ('DBA', 'DBA', 1, 1, 2);
MERGE INTO SYS_ROLE t
USING (SELECT 'OPS' AS c FROM DUAL) s ON (t.ROLE_CODE = s.c)
WHEN NOT MATCHED THEN INSERT (ROLE_CODE, ROLE_NAME, STATUS, IS_SYSTEM, SORT_ORDER)
  VALUES ('OPS', '运维工程师', 1, 1, 3);
MERGE INTO SYS_ROLE t
USING (SELECT 'REVIEWER' AS c FROM DUAL) s ON (t.ROLE_CODE = s.c)
WHEN NOT MATCHED THEN INSERT (ROLE_CODE, ROLE_NAME, STATUS, IS_SYSTEM, SORT_ORDER)
  VALUES ('REVIEWER', '审核员', 1, 1, 4);
MERGE INTO SYS_ROLE t
USING (SELECT 'VIEWER' AS c FROM DUAL) s ON (t.ROLE_CODE = s.c)
WHEN NOT MATCHED THEN INSERT (ROLE_CODE, ROLE_NAME, STATUS, IS_SYSTEM, SORT_ORDER)
  VALUES ('VIEWER', '只读用户', 1, 1, 5);
MERGE INTO SYS_ROLE t
USING (SELECT 'DEV' AS c FROM DUAL) s ON (t.ROLE_CODE = s.c)
WHEN NOT MATCHED THEN INSERT (ROLE_CODE, ROLE_NAME, STATUS, IS_SYSTEM, SORT_ORDER)
  VALUES ('DEV', '开发人员', 1, 1, 6);

-- ========== 种子：菜单 ==========
MERGE INTO SYS_MENU t
USING (SELECT '/dashboard' AS p FROM DUAL) s ON (t.MENU_PATH = s.p)
WHEN NOT MATCHED THEN INSERT (MENU_PATH, MENU_NAME, SORT_ORDER) VALUES ('/dashboard', '控制台', 10);
MERGE INTO SYS_MENU t
USING (SELECT '/monitor' AS p FROM DUAL) s ON (t.MENU_PATH = s.p)
WHEN NOT MATCHED THEN INSERT (MENU_PATH, MENU_NAME, SORT_ORDER) VALUES ('/monitor', '监控中心', 20);
MERGE INTO SYS_MENU t
USING (SELECT '/monitor/collect-scheduler' AS p FROM DUAL) s ON (t.MENU_PATH = s.p)
WHEN NOT MATCHED THEN INSERT (MENU_PATH, MENU_NAME, SORT_ORDER) VALUES ('/monitor/collect-scheduler', '定时采集观测', 30);
MERGE INTO SYS_MENU t
USING (SELECT '/alerts' AS p FROM DUAL) s ON (t.MENU_PATH = s.p)
WHEN NOT MATCHED THEN INSERT (MENU_PATH, MENU_NAME, SORT_ORDER) VALUES ('/alerts', '告警中心', 40);
MERGE INTO SYS_MENU t
USING (SELECT '/cmdb' AS p FROM DUAL) s ON (t.MENU_PATH = s.p)
WHEN NOT MATCHED THEN INSERT (MENU_PATH, MENU_NAME, SORT_ORDER) VALUES ('/cmdb', '资产管理', 50);
MERGE INTO SYS_MENU t
USING (SELECT '/automation' AS p FROM DUAL) s ON (t.MENU_PATH = s.p)
WHEN NOT MATCHED THEN INSERT (MENU_PATH, MENU_NAME, SORT_ORDER) VALUES ('/automation', '自动化运维', 60);
MERGE INTO SYS_MENU t
USING (SELECT '/sql' AS p FROM DUAL) s ON (t.MENU_PATH = s.p)
WHEN NOT MATCHED THEN INSERT (MENU_PATH, MENU_NAME, SORT_ORDER) VALUES ('/sql', 'SQL优化', 70);
MERGE INTO SYS_MENU t
USING (SELECT '/reports' AS p FROM DUAL) s ON (t.MENU_PATH = s.p)
WHEN NOT MATCHED THEN INSERT (MENU_PATH, MENU_NAME, SORT_ORDER) VALUES ('/reports', '报表中心', 80);
MERGE INTO SYS_MENU t
USING (SELECT '/ai' AS p FROM DUAL) s ON (t.MENU_PATH = s.p)
WHEN NOT MATCHED THEN INSERT (MENU_PATH, MENU_NAME, SORT_ORDER) VALUES ('/ai', 'AI 智能分析', 90);
MERGE INTO SYS_MENU t
USING (SELECT '/settings/profile' AS p FROM DUAL) s ON (t.MENU_PATH = s.p)
WHEN NOT MATCHED THEN INSERT (MENU_PATH, MENU_NAME, SORT_ORDER) VALUES ('/settings/profile', '个人设置', 100);
MERGE INTO SYS_MENU t
USING (SELECT '/settings/users' AS p FROM DUAL) s ON (t.MENU_PATH = s.p)
WHEN NOT MATCHED THEN INSERT (MENU_PATH, MENU_NAME, SORT_ORDER) VALUES ('/settings/users', '用户管理', 110);
MERGE INTO SYS_MENU t
USING (SELECT '/settings/roles' AS p FROM DUAL) s ON (t.MENU_PATH = s.p)
WHEN NOT MATCHED THEN INSERT (MENU_PATH, MENU_NAME, SORT_ORDER) VALUES ('/settings/roles', '角色权限', 120);

-- ========== 种子：ADMIN = 全部菜单 ==========
INSERT INTO SYS_ROLE_MENU (ROLE_ID, MENU_ID)
SELECT r.ROLE_ID, m.MENU_ID
FROM SYS_ROLE r
CROSS JOIN SYS_MENU m
WHERE r.ROLE_CODE = 'ADMIN'
  AND NOT EXISTS (
    SELECT 1 FROM SYS_ROLE_MENU x WHERE x.ROLE_ID = r.ROLE_ID AND x.MENU_ID = m.MENU_ID
  );

-- DBA/OPS/REVIEWER/DEV：除「用户管理」「角色权限」外全部（可按需在界面调整）
INSERT INTO SYS_ROLE_MENU (ROLE_ID, MENU_ID)
SELECT r.ROLE_ID, m.MENU_ID
FROM SYS_ROLE r
JOIN SYS_MENU m ON m.MENU_PATH NOT IN ('/settings/users', '/settings/roles')
WHERE r.ROLE_CODE IN ('DBA', 'OPS', 'REVIEWER', 'DEV')
  AND NOT EXISTS (
    SELECT 1 FROM SYS_ROLE_MENU x WHERE x.ROLE_ID = r.ROLE_ID AND x.MENU_ID = m.MENU_ID
  );

-- VIEWER：控制台 + 监控 + 告警 + 个人设置（可按需在界面调整）
INSERT INTO SYS_ROLE_MENU (ROLE_ID, MENU_ID)
SELECT r.ROLE_ID, m.MENU_ID
FROM SYS_ROLE r
JOIN SYS_MENU m ON m.MENU_PATH IN ('/dashboard', '/monitor', '/monitor/collect-scheduler', '/alerts', '/settings/profile')
WHERE r.ROLE_CODE = 'VIEWER'
  AND NOT EXISTS (
    SELECT 1 FROM SYS_ROLE_MENU x WHERE x.ROLE_ID = r.ROLE_ID AND x.MENU_ID = m.MENU_ID
  );

COMMIT;
