-- ============================================================
-- DIOps v2 — 自动化运维专业版增量表结构
-- 包含：自动巡检、自动故障处理、自动发布、SQL治理、
--       HA管理、容量预测、备份恢复中心
-- 执行前确认：以 monitor 用户（或有建表权限的用户）执行
-- ============================================================

-- ============================================================
-- 1. 自动巡检 Inspect Pro
-- ============================================================

-- 巡检脚本库（支持多数据库类型，模板上传）
CREATE TABLE INSPECT_SCRIPT (
  SCRIPT_ID      NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  SCRIPT_NAME    VARCHAR2(128) NOT NULL,
  DB_TYPE        VARCHAR2(32)  NOT NULL, -- ORACLE/MYSQL/POSTGRESQL/DAMENG/GOLDENDB
  CATEGORY       VARCHAR2(64)  NOT NULL, -- HEALTH/RISK/PARAMETER/SPACE/HA
  SCRIPT_CONTENT CLOB,
  VERSION        VARCHAR2(32)  DEFAULT '1.0',
  IS_TEMPLATE    NUMBER(1)     DEFAULT 0,
  ENABLED        NUMBER(1)     DEFAULT 1,
  CREATED_BY     NUMBER,
  CREATED_AT     TIMESTAMP     DEFAULT SYSTIMESTAMP,
  UPDATED_AT     TIMESTAMP     DEFAULT SYSTIMESTAMP
);
COMMENT ON TABLE INSPECT_SCRIPT IS '巡检脚本库（多数据库类型）';
CREATE INDEX IDX_INSP_SCRIPT_TYPE ON INSPECT_SCRIPT(DB_TYPE, CATEGORY);

-- 巡检任务（取代旧 AUTOMATION_INSPECT_BATCH）
CREATE TABLE INSPECT_TASK (
  TASK_ID        NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  TASK_NAME      VARCHAR2(128) NOT NULL,
  DB_TYPE        VARCHAR2(32),               -- 为空=全部类型
  INSTANCE_IDS   VARCHAR2(4000),             -- JSON数组
  SCRIPT_IDS     VARCHAR2(4000),             -- JSON数组
  CRON_EXPR      VARCHAR2(64),               -- 定时表达式
  STATUS         VARCHAR2(32) DEFAULT 'IDLE',-- IDLE/RUNNING/DONE/FAILED
  LAST_RUN_AT    TIMESTAMP,
  NEXT_RUN_AT    TIMESTAMP,
  CREATED_BY     NUMBER,
  CREATED_AT     TIMESTAMP    DEFAULT SYSTIMESTAMP
);
COMMENT ON TABLE INSPECT_TASK IS '巡检任务（定时/手动）';

-- 巡检报告（每次执行生成）
CREATE TABLE INSPECT_REPORT (
  REPORT_ID        NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  TASK_ID          NUMBER,
  INSTANCE_ID      NUMBER       NOT NULL,
  DB_TYPE          VARCHAR2(32) NOT NULL,
  REPORT_TYPE      VARCHAR2(32) NOT NULL, -- HEALTH/RISK/PARAMETER/SPACE/HA
  OVERALL_SCORE    NUMBER(5,1),
  OVERALL_STATUS   VARCHAR2(16),          -- NORMAL/WARNING/CRITICAL
  SUMMARY          VARCHAR2(4000),
  PAYLOAD          CLOB,                  -- JSON详情
  EXECUTED_AT      TIMESTAMP    DEFAULT SYSTIMESTAMP,
  CREATED_BY       NUMBER,
  CREATED_AT       TIMESTAMP    DEFAULT SYSTIMESTAMP
);
COMMENT ON TABLE INSPECT_REPORT IS '巡检报告（五类）';
CREATE INDEX IDX_INSP_RPT_INST ON INSPECT_REPORT(INSTANCE_ID, REPORT_TYPE, CREATED_AT DESC);
CREATE INDEX IDX_INSP_RPT_TASK ON INSPECT_REPORT(TASK_ID);

-- 巡检问题明细
CREATE TABLE INSPECT_ISSUE (
  ISSUE_ID     NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  REPORT_ID    NUMBER       NOT NULL,
  INSTANCE_ID  NUMBER       NOT NULL,
  CATEGORY     VARCHAR2(64) NOT NULL,
  SEVERITY     VARCHAR2(16) NOT NULL, -- CRITICAL/WARNING/INFO
  TITLE        VARCHAR2(256),
  DESCRIPTION  VARCHAR2(4000),
  ADVICE       VARCHAR2(4000),
  METRIC_KEY   VARCHAR2(128),
  METRIC_VALUE VARCHAR2(256),
  THRESHOLD    VARCHAR2(256),
  CREATED_AT   TIMESTAMP DEFAULT SYSTIMESTAMP
);
CREATE INDEX IDX_INSP_ISSUE_RPT ON INSPECT_ISSUE(REPORT_ID);
CREATE INDEX IDX_INSP_ISSUE_INST ON INSPECT_ISSUE(INSTANCE_ID, SEVERITY);

-- ============================================================
-- 2. 自动故障处理 Auto-Fault
-- ============================================================

-- 故障处理策略
CREATE TABLE FAULT_POLICY (
  POLICY_ID      NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  POLICY_NAME    VARCHAR2(128) NOT NULL,
  DB_TYPE        VARCHAR2(32)  NOT NULL, -- MYSQL/ORACLE/POSTGRESQL
  FAULT_TYPE     VARCHAR2(64)  NOT NULL, -- REPL_DELAY/REPL_BROKEN/DISK_FULL/TEMP_FULL/FRA_FULL/SESSION_ABNORMAL
  CONDITION_JSON CLOB,                   -- 触发条件JSON
  ACTION_TYPE    VARCHAR2(64)  NOT NULL, -- AUTO_FIX/ALERT_ONLY/MANUAL
  ACTION_SCRIPT  CLOB,                   -- 修复脚本/命令
  ENABLED        NUMBER(1)     DEFAULT 1,
  INSTANCE_IDS   VARCHAR2(4000),         -- 适用实例（空=全部）
  CREATED_BY     NUMBER,
  CREATED_AT     TIMESTAMP DEFAULT SYSTIMESTAMP,
  UPDATED_AT     TIMESTAMP DEFAULT SYSTIMESTAMP
);
COMMENT ON TABLE FAULT_POLICY IS '故障自动处理策略';
CREATE INDEX IDX_FAULT_POL_TYPE ON FAULT_POLICY(DB_TYPE, FAULT_TYPE);

-- 故障处理执行记录
CREATE TABLE FAULT_EXEC_LOG (
  LOG_ID         NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  POLICY_ID      NUMBER,
  INSTANCE_ID    NUMBER       NOT NULL,
  FAULT_TYPE     VARCHAR2(64) NOT NULL,
  TRIGGER_SOURCE VARCHAR2(32) DEFAULT 'AUTO',  -- AUTO/MANUAL
  STATUS         VARCHAR2(32) NOT NULL,         -- SUCCESS/FAILED/RUNNING/SKIPPED
  DETAIL         CLOB,
  STARTED_AT     TIMESTAMP    DEFAULT SYSTIMESTAMP,
  FINISHED_AT    TIMESTAMP,
  CREATED_BY     NUMBER,
  CREATED_AT     TIMESTAMP    DEFAULT SYSTIMESTAMP
);
CREATE INDEX IDX_FAULT_LOG_INST ON FAULT_EXEC_LOG(INSTANCE_ID, CREATED_AT DESC);
CREATE INDEX IDX_FAULT_LOG_POL ON FAULT_EXEC_LOG(POLICY_ID);

-- ============================================================
-- 3. 自动发布 Auto-Publish (SQL/DDL)
-- ============================================================

-- 发布工单
CREATE TABLE PUBLISH_TICKET (
  TICKET_ID       NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  TICKET_NO       VARCHAR2(64)  UNIQUE,       -- 工单号 PUB-20260514-001
  TITLE           VARCHAR2(256) NOT NULL,
  TICKET_TYPE     VARCHAR2(32)  NOT NULL,      -- SQL_PUBLISH/DDL_REVIEW
  INSTANCE_ID     NUMBER,
  DB_NAME         VARCHAR2(128),
  SQL_CONTENT     CLOB          NOT NULL,
  ROLLBACK_SQL    CLOB,
  STATUS          VARCHAR2(32)  DEFAULT 'DRAFT', -- DRAFT/REVIEWING/APPROVED/REJECTED/GRAY/RUNNING/DONE/ROLLED_BACK
  GRAY_PERCENT    NUMBER        DEFAULT 0,        -- 灰度比例 0-100
  RISK_LEVEL      VARCHAR2(16),                   -- LOW/MEDIUM/HIGH/CRITICAL
  REVIEW_RESULT   CLOB,                           -- 审核意见JSON
  EXEC_PLAN       CLOB,                           -- 执行计划
  EXEC_RESULT     CLOB,                           -- 执行结果
  SUBMITTED_BY    NUMBER,
  REVIEWED_BY     NUMBER,
  REVIEWED_AT     TIMESTAMP,
  EXECUTED_BY     NUMBER,
  EXECUTED_AT     TIMESTAMP,
  CREATED_AT      TIMESTAMP DEFAULT SYSTIMESTAMP,
  UPDATED_AT      TIMESTAMP DEFAULT SYSTIMESTAMP
);
COMMENT ON TABLE PUBLISH_TICKET IS '自动发布工单（SQL/DDL）';
CREATE INDEX IDX_PUB_TICK_STATUS ON PUBLISH_TICKET(STATUS, CREATED_AT DESC);
CREATE INDEX IDX_PUB_TICK_INST ON PUBLISH_TICKET(INSTANCE_ID);

-- 发布审核记录
CREATE TABLE PUBLISH_REVIEW (
  REVIEW_ID    NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  TICKET_ID    NUMBER NOT NULL,
  ACTION       VARCHAR2(32) NOT NULL, -- APPROVE/REJECT/COMMENT/ROLLBACK
  "COMMENT"      VARCHAR2(2000),
  OPERATED_BY  NUMBER,
  CREATED_AT   TIMESTAMP DEFAULT SYSTIMESTAMP
);
CREATE INDEX IDX_PUB_REV_TICK ON PUBLISH_REVIEW(TICKET_ID);

-- DDL审核规则
CREATE TABLE DDL_AUDIT_RULE (
  RULE_ID      NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  RULE_NAME    VARCHAR2(128) NOT NULL,
  RULE_CODE    VARCHAR2(64)  UNIQUE,
  DB_TYPE      VARCHAR2(32) DEFAULT 'ALL',
  RULE_PATTERN VARCHAR2(2000),
  SEVERITY     VARCHAR2(16) DEFAULT 'WARNING',
  MESSAGE      VARCHAR2(512),
  ENABLED      NUMBER(1) DEFAULT 1,
  CREATED_AT   TIMESTAMP DEFAULT SYSTIMESTAMP
);
COMMENT ON TABLE DDL_AUDIT_RULE IS 'DDL/SQL审核规则';

-- 内置审核规则种子数据
INSERT INTO DDL_AUDIT_RULE (RULE_NAME,RULE_CODE,DB_TYPE,RULE_PATTERN,SEVERITY,MESSAGE) VALUES
('禁止SELECT *','NO_SELECT_STAR','ALL','SELECT\s*\*','ERROR','禁止使用SELECT *，请明确列名');
INSERT INTO DDL_AUDIT_RULE (RULE_NAME,RULE_CODE,DB_TYPE,RULE_PATTERN,SEVERITY,MESSAGE) VALUES
('必须携带WHERE条件','WHERE_REQUIRED','ALL','(DELETE|UPDATE)\s+\w+\s+(?!.*WHERE)','ERROR','DELETE/UPDATE必须携带WHERE条件');
INSERT INTO DDL_AUDIT_RULE (RULE_NAME,RULE_CODE,DB_TYPE,RULE_PATTERN,SEVERITY,MESSAGE) VALUES
('大表禁止直接DELETE','NO_DELETE_LARGE_TABLE','ALL','DELETE\s+FROM\s+\w+(?!.*WHERE.*ID)','WARNING','大表（>100w行）禁止全表DELETE，请使用分批删除');
INSERT INTO DDL_AUDIT_RULE (RULE_NAME,RULE_CODE,DB_TYPE,RULE_PATTERN,SEVERITY,MESSAGE) VALUES
('禁止隐式类型转换','NO_IMPLICIT_CONVERT','ALL','WHERE\s+\w+\s*=\s*\'?\d+\'?','WARNING','WHERE条件中存在隐式类型转换风险');
INSERT INTO DDL_AUDIT_RULE (RULE_NAME,RULE_CODE,DB_TYPE,RULE_PATTERN,SEVERITY,MESSAGE) VALUES
('禁止DROP TABLE','NO_DROP_TABLE','ALL','DROP\s+TABLE','CRITICAL','禁止直接DROP TABLE，需通过申请流程');
INSERT INTO DDL_AUDIT_RULE (RULE_NAME,RULE_CODE,DB_TYPE,RULE_PATTERN,SEVERITY,MESSAGE) VALUES
('新增列需设默认值','ADD_COL_DEFAULT','ALL','ADD\s+COLUMN\s+\w+\s+\w+(?!.*DEFAULT)','WARNING','新增列建议设置DEFAULT值');
COMMIT;

-- ============================================================
-- 4. SQL治理中心 SQL-Governance
-- ============================================================

-- SQL审核记录
CREATE TABLE SQL_AUDIT_RECORD (
  AUDIT_ID       NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  INSTANCE_ID    NUMBER,
  SQL_TEXT       CLOB         NOT NULL,
  SQL_HASH       VARCHAR2(64),
  AUDIT_RESULT   CLOB,                    -- JSON: [{rule,severity,message}]
  SCORE          NUMBER(5,1)  DEFAULT 100,
  RISK_LEVEL     VARCHAR2(16),
  SUBMITTED_BY   NUMBER,
  CREATED_AT     TIMESTAMP DEFAULT SYSTIMESTAMP
);
CREATE INDEX IDX_SQL_AUDIT_HASH ON SQL_AUDIT_RECORD(SQL_HASH);
CREATE INDEX IDX_SQL_AUDIT_INST ON SQL_AUDIT_RECORD(INSTANCE_ID, CREATED_AT DESC);

-- SQL基线（执行计划固化）
CREATE TABLE SQL_BASELINE (
  BASELINE_ID    NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  SQL_HASH       VARCHAR2(64) NOT NULL,
  SQL_TEXT       CLOB,
  INSTANCE_ID    NUMBER,
  EXEC_PLAN      CLOB,          -- 基线执行计划JSON
  BASELINE_TYPE  VARCHAR2(32) DEFAULT 'FIXED', -- FIXED/APPROVED/EVOLVED
  STATUS         VARCHAR2(32) DEFAULT 'ACTIVE',
  CREATED_BY     NUMBER,
  CREATED_AT     TIMESTAMP DEFAULT SYSTIMESTAMP,
  UPDATED_AT     TIMESTAMP DEFAULT SYSTIMESTAMP
);
CREATE INDEX IDX_SQL_BASE_HASH ON SQL_BASELINE(SQL_HASH, STATUS);
CREATE UNIQUE INDEX UDX_SQL_BASE_HASH_INST ON SQL_BASELINE(SQL_HASH, INSTANCE_ID);

-- SQL回归分析记录
CREATE TABLE SQL_REGRESSION (
  REGRESSION_ID   NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  SQL_HASH        VARCHAR2(64) NOT NULL,
  INSTANCE_ID     NUMBER,
  BASELINE_PLAN   CLOB,
  CURRENT_PLAN    CLOB,
  BASELINE_COST   NUMBER,
  CURRENT_COST    NUMBER,
  REGRESSED       NUMBER(1) DEFAULT 0,   -- 1=退化
  DETAIL          VARCHAR2(4000),
  CHECKED_AT      TIMESTAMP DEFAULT SYSTIMESTAMP
);
CREATE INDEX IDX_SQL_REG_HASH ON SQL_REGRESSION(SQL_HASH, INSTANCE_ID);

-- SQL评分维度配置
CREATE TABLE SQL_SCORE_CONFIG (
  CONFIG_ID    NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  DIMENSION    VARCHAR2(64) NOT NULL, -- INDEX/ROWS/CPU/IO/RISK
  WEIGHT       NUMBER(5,2)  DEFAULT 20,
  DESCRIPTION  VARCHAR2(256),
  UPDATED_AT   TIMESTAMP DEFAULT SYSTIMESTAMP
);
INSERT INTO SQL_SCORE_CONFIG (DIMENSION,WEIGHT,DESCRIPTION) VALUES ('INDEX',25,'索引使用情况');
INSERT INTO SQL_SCORE_CONFIG (DIMENSION,WEIGHT,DESCRIPTION) VALUES ('ROWS',20,'扫描行数/返回行数比');
INSERT INTO SQL_SCORE_CONFIG (DIMENSION,WEIGHT,DESCRIPTION) VALUES ('CPU',20,'CPU消耗估算');
INSERT INTO SQL_SCORE_CONFIG (DIMENSION,WEIGHT,DESCRIPTION) VALUES ('IO',20,'IO操作次数');
INSERT INTO SQL_SCORE_CONFIG (DIMENSION,WEIGHT,DESCRIPTION) VALUES ('RISK',15,'风险规则违反');
COMMIT;

-- ============================================================
-- 5. 高可用与容灾管理 HA-Pro
-- ============================================================

-- HA拓扑（统一管理各类高可用架构）
CREATE TABLE HA_TOPOLOGY (
  TOPO_ID      NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  TOPO_NAME    VARCHAR2(128) NOT NULL,
  HA_TYPE      VARCHAR2(32)  NOT NULL, -- MGR/PXC/ADG/RAC/REPLICATION/SENTINEL
  PRIMARY_ID   NUMBER,                 -- 主节点INSTANCE_ID
  MEMBER_IDS   VARCHAR2(4000),         -- JSON节点列表
  VIP          VARCHAR2(128),
  STATUS       VARCHAR2(32) DEFAULT 'NORMAL', -- NORMAL/WARNING/FAILOVER/MAINTENANCE
  REGION_INFO  CLOB,                   -- 多活地域JSON
  CONFIG_JSON  CLOB,                   -- 拓扑配置
  ENABLED      NUMBER(1) DEFAULT 1,
  CREATED_AT   TIMESTAMP DEFAULT SYSTIMESTAMP,
  UPDATED_AT   TIMESTAMP DEFAULT SYSTIMESTAMP
);
COMMENT ON TABLE HA_TOPOLOGY IS 'HA拓扑统一管理（MGR/PXC/ADG/RAC等）';

-- HA切换记录
CREATE TABLE HA_SWITCH_RECORD (
  SWITCH_ID    NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  TOPO_ID      NUMBER       NOT NULL,
  SWITCH_TYPE  VARCHAR2(32) NOT NULL, -- PLANNED/FAILOVER/DRILL
  FROM_NODE    NUMBER,
  TO_NODE      NUMBER,
  STATUS       VARCHAR2(32) DEFAULT 'PENDING',
  PRECHECK     CLOB,                   -- 预检JSON
  RESULT       CLOB,
  OPERATED_BY  NUMBER,
  STARTED_AT   TIMESTAMP DEFAULT SYSTIMESTAMP,
  FINISHED_AT  TIMESTAMP,
  CREATED_AT   TIMESTAMP DEFAULT SYSTIMESTAMP
);
CREATE INDEX IDX_HA_SWITCH_TOPO ON HA_SWITCH_RECORD(TOPO_ID, CREATED_AT DESC);

-- 容灾链路状态（北京->上海->深圳等）
CREATE TABLE DR_LINK (
  LINK_ID       NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  LINK_NAME     VARCHAR2(128) NOT NULL,
  SOURCE_REGION VARCHAR2(64)  NOT NULL,
  TARGET_REGION VARCHAR2(64)  NOT NULL,
  SOURCE_ID     NUMBER,
  TARGET_ID     NUMBER,
  SYNC_MODE     VARCHAR2(32) DEFAULT 'ASYNC', -- SYNC/ASYNC/SEMI_SYNC
  LINK_STATUS   VARCHAR2(32) DEFAULT 'NORMAL',-- NORMAL/LAG/BROKEN/FAILOVER
  SYNC_DELAY_MS NUMBER,
  RPO_SEC       NUMBER,
  RTO_SEC       NUMBER,
  LAST_CHECK_AT TIMESTAMP,
  CREATED_AT    TIMESTAMP DEFAULT SYSTIMESTAMP,
  UPDATED_AT    TIMESTAMP DEFAULT SYSTIMESTAMP
);
COMMENT ON TABLE DR_LINK IS '容灾链路（多活/主备）';

-- ============================================================
-- 6. 容量预测与成本分析
-- ============================================================

-- 容量基线快照（每日采集）
CREATE TABLE CAPACITY_SNAPSHOT (
  SNAP_ID      NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  INSTANCE_ID  NUMBER       NOT NULL,
  SNAP_DATE    DATE         NOT NULL,
  DISK_USED_GB NUMBER(10,2),
  DISK_TOTAL_GB NUMBER(10,2),
  TABLE_COUNT  NUMBER,
  TOP_TABLE_JSON CLOB,               -- Top20大表JSON
  TPS_AVG      NUMBER(10,2),
  TPS_PEAK     NUMBER(10,2),
  QPS_AVG      NUMBER(10,2),
  CONN_AVG     NUMBER,
  CPU_AVG_PCT  NUMBER(5,2),
  MEM_AVG_PCT  NUMBER(5,2),
  CREATED_AT   TIMESTAMP DEFAULT SYSTIMESTAMP
);
CREATE UNIQUE INDEX UDX_CAP_SNAP ON CAPACITY_SNAPSHOT(INSTANCE_ID, SNAP_DATE);
CREATE INDEX IDX_CAP_SNAP_INST ON CAPACITY_SNAPSHOT(INSTANCE_ID, SNAP_DATE DESC);

-- 容量预测结果
CREATE TABLE CAPACITY_FORECAST (
  FORECAST_ID   NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  INSTANCE_ID   NUMBER       NOT NULL,
  FORECAST_DATE DATE         NOT NULL,
  METRIC_TYPE   VARCHAR2(32) NOT NULL, -- DISK/TABLE_ROWS/TPS
  FORECAST_VAL  NUMBER(15,4) NOT NULL,
  LOWER_BOUND   NUMBER(15,4),
  UPPER_BOUND   NUMBER(15,4),
  CONFIDENCE    NUMBER(5,2),
  DAYS_TO_FULL  NUMBER,               -- 预计满员天数
  CREATED_AT    TIMESTAMP DEFAULT SYSTIMESTAMP
);
CREATE INDEX IDX_CAP_FORE_INST ON CAPACITY_FORECAST(INSTANCE_ID, METRIC_TYPE, FORECAST_DATE);

-- 成本分析记录
CREATE TABLE COST_ANALYSIS (
  ANALYSIS_ID   NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  ANALYSIS_DATE DATE         NOT NULL,
  INSTANCE_ID   NUMBER,
  BUSINESS_TAG  VARCHAR2(128),
  CPU_COST_UNIT NUMBER(10,4),         -- CPU消耗单位
  IO_COST_UNIT  NUMBER(10,4),
  MEM_COST_UNIT NUMBER(10,4),
  TOP_SQL_JSON  CLOB,                 -- 最贵SQL TOP10
  WASTE_PCT     NUMBER(5,2),          -- 资源浪费率
  SCORE         NUMBER(5,1),          -- 资源利用评分
  CREATED_AT    TIMESTAMP DEFAULT SYSTIMESTAMP
);
CREATE INDEX IDX_COST_ANA_DATE ON COST_ANALYSIS(ANALYSIS_DATE DESC, INSTANCE_ID);

-- ============================================================
-- 7. 备份恢复中心 Backup Center Pro
-- ============================================================

-- 备份策略（扩展版）
CREATE TABLE BACKUP_POLICY_PRO (
  POLICY_ID     NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  POLICY_NAME   VARCHAR2(128) NOT NULL,
  INSTANCE_ID   NUMBER,
  BACKUP_TYPE   VARCHAR2(32)  NOT NULL, -- FULL/INCREMENTAL/LOGICAL/PHYSICAL
  STORAGE_TYPE  VARCHAR2(32) DEFAULT 'LOCAL', -- LOCAL/NFS/S3/OSS
  STORAGE_PATH  VARCHAR2(512),
  RETENTION_DAYS NUMBER DEFAULT 7,
  "COMPRESS"     NUMBER(1) DEFAULT 1,
  ENCRYPT       NUMBER(1) DEFAULT 0,
  SCHEDULE      VARCHAR2(64),           -- Cron表达式
  ENABLED       NUMBER(1) DEFAULT 1,
  LAST_RUN_AT   TIMESTAMP,
  CREATED_BY    NUMBER,
  CREATED_AT    TIMESTAMP DEFAULT SYSTIMESTAMP,
  UPDATED_AT    TIMESTAMP DEFAULT SYSTIMESTAMP
);
COMMENT ON TABLE BACKUP_POLICY_PRO IS '备份策略（全/增/逻辑/物理）';

-- 备份记录（扩展版）
CREATE TABLE BACKUP_RECORD_PRO (
  RECORD_ID      NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  POLICY_ID      NUMBER,
  INSTANCE_ID    NUMBER       NOT NULL,
  BACKUP_TYPE    VARCHAR2(32) NOT NULL,
  STATUS         VARCHAR2(32) DEFAULT 'PENDING', -- PENDING/RUNNING/SUCCESS/FAILED
  FILE_PATH      VARCHAR2(1024),
  FILE_SIZE_MB   NUMBER(15,2),
  CHECKSUM       VARCHAR2(64),
  START_TIME     TIMESTAMP,
  END_TIME       TIMESTAMP,
  DURATION_SEC   NUMBER,
  ERROR_MSG      VARCHAR2(2000),
  TRIGGER_TYPE   VARCHAR2(32) DEFAULT 'SCHEDULED', -- SCHEDULED/MANUAL
  CREATED_BY     NUMBER,
  CREATED_AT     TIMESTAMP DEFAULT SYSTIMESTAMP
);
CREATE INDEX IDX_BKP_REC_INST ON BACKUP_RECORD_PRO(INSTANCE_ID, START_TIME DESC);
CREATE INDEX IDX_BKP_REC_STATUS ON BACKUP_RECORD_PRO(STATUS, CREATED_AT DESC);

-- 恢复任务
CREATE TABLE RESTORE_TASK (
  RESTORE_ID     NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  RECORD_ID      NUMBER,               -- 关联备份记录
  INSTANCE_ID    NUMBER       NOT NULL,
  RESTORE_TYPE   VARCHAR2(32) NOT NULL, -- PITR/SINGLE_TABLE/FLASHBACK/FULL
  TARGET_TIME    TIMESTAMP,             -- PITR目标时间
  TARGET_TABLE   VARCHAR2(256),         -- 单表恢复
  FLASHBACK_SCN  NUMBER,               -- 闪回SCN
  STATUS         VARCHAR2(32) DEFAULT 'PENDING',
  RESULT         CLOB,
  STARTED_AT     TIMESTAMP DEFAULT SYSTIMESTAMP,
  FINISHED_AT    TIMESTAMP,
  CREATED_BY     NUMBER,
  CREATED_AT     TIMESTAMP DEFAULT SYSTIMESTAMP
);
CREATE INDEX IDX_RESTORE_INST ON RESTORE_TASK(INSTANCE_ID, CREATED_AT DESC);

COMMIT;
-- ============================================================
-- END
-- ============================================================
