-- 已有环境增量：监控采集样本表（执行一次）
-- sqlplus user/pass@conn @migration_monitor_metric_sample.sql

CREATE TABLE MONITOR_METRIC_SAMPLE (
  SAMPLE_ID     NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  INSTANCE_ID   NUMBER        NOT NULL,
  COLLECTED_AT  TIMESTAMP     DEFAULT SYSTIMESTAMP NOT NULL,
  DB_TYPE       VARCHAR2(32),
  REACHABLE     NUMBER(1)     DEFAULT 1 NOT NULL,
  HEALTH_SCORE  NUMBER(3),
  METRIC_CPU    NUMBER,
  METRIC_CONN   NUMBER,
  METRICS_JSON  CLOB,
  ERR_MSG       VARCHAR2(512)
);

COMMENT ON TABLE MONITOR_METRIC_SAMPLE IS '被管库周期/即时采集快照';
CREATE INDEX IDX_MON_SAMPLE_INST_TIME ON MONITOR_METRIC_SAMPLE(INSTANCE_ID, COLLECTED_AT DESC);

COMMIT;
