-- ============================================================
-- F-24 Web SQL 工作台 — 执行历史表
-- ============================================================

CREATE TABLE SQL_WORKBENCH_HISTORY (
  HISTORY_ID    NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  INSTANCE_ID   NUMBER NOT NULL,
  SQL_TEXT      CLOB NOT NULL,
  ROW_COUNT     NUMBER DEFAULT 0,
  ELAPSED_MS    NUMBER DEFAULT 0,
  CREATED_BY    VARCHAR2(64),
  CREATED_AT    TIMESTAMP DEFAULT SYSTIMESTAMP
);

COMMENT ON TABLE SQL_WORKBENCH_HISTORY IS 'F-24 Web SQL 工作台执行历史';

CREATE INDEX IDX_WB_HISTORY_INST ON SQL_WORKBENCH_HISTORY(INSTANCE_ID, CREATED_AT DESC);

COMMIT;
