-- F-50 运维服务化：增强服务目录 + 工单系统
-- 在 init.sql 已有 OPS_SERVICE_CATALOG / OPS_SERVICE_ORDER 基础上增加字段

-- ============================================================
-- 1. OPS_SERVICE_CATALOG 增强字段
-- ============================================================
BEGIN
  EXECUTE IMMEDIATE 'ALTER TABLE OPS_SERVICE_CATALOG ADD (ICON VARCHAR2(64))';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -1430 THEN RAISE; END IF; END;
/
BEGIN
  EXECUTE IMMEDIATE 'ALTER TABLE OPS_SERVICE_CATALOG ADD (SORT_ORDER NUMBER DEFAULT 0)';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -1430 THEN RAISE; END IF; END;
/
BEGIN
  EXECUTE IMMEDIATE 'ALTER TABLE OPS_SERVICE_CATALOG ADD (ENABLED NUMBER(1) DEFAULT 1)';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -1430 THEN RAISE; END IF; END;
/
BEGIN
  EXECUTE IMMEDIATE 'ALTER TABLE OPS_SERVICE_CATALOG ADD (SLA_HOURS NUMBER)';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -1430 THEN RAISE; END IF; END;
/
BEGIN
  EXECUTE IMMEDIATE 'ALTER TABLE OPS_SERVICE_CATALOG ADD (ASSIGNEE_ROLE VARCHAR2(32))';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -1430 THEN RAISE; END IF; END;
/
BEGIN
  EXECUTE IMMEDIATE 'ALTER TABLE OPS_SERVICE_CATALOG ADD (UPDATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP)';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -1430 THEN RAISE; END IF; END;
/

-- ============================================================
-- 2. OPS_SERVICE_ORDER 增强字段
-- ============================================================
BEGIN
  EXECUTE IMMEDIATE 'ALTER TABLE OPS_SERVICE_ORDER ADD (TITLE VARCHAR2(256))';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -1430 THEN RAISE; END IF; END;
/
BEGIN
  EXECUTE IMMEDIATE 'ALTER TABLE OPS_SERVICE_ORDER ADD (PRIORITY VARCHAR2(16) DEFAULT ''MEDIUM'')';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -1430 THEN RAISE; END IF; END;
/
BEGIN
  EXECUTE IMMEDIATE 'ALTER TABLE OPS_SERVICE_ORDER ADD (ASSIGNED_TO NUMBER)';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -1430 THEN RAISE; END IF; END;
/
BEGIN
  EXECUTE IMMEDIATE 'ALTER TABLE OPS_SERVICE_ORDER ADD (UPDATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP)';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -1430 THEN RAISE; END IF; END;
/
BEGIN
  EXECUTE IMMEDIATE 'ALTER TABLE OPS_SERVICE_ORDER ADD (RESOLVED_AT TIMESTAMP)';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -1430 THEN RAISE; END IF; END;
/
BEGIN
  EXECUTE IMMEDIATE 'ALTER TABLE OPS_SERVICE_ORDER ADD (CLOSED_AT TIMESTAMP)';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -1430 THEN RAISE; END IF; END;
/
BEGIN
  EXECUTE IMMEDIATE 'ALTER TABLE OPS_SERVICE_ORDER ADD (FEEDBACK_SCORE NUMBER(1))';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -1430 THEN RAISE; END IF; END;
/
BEGIN
  EXECUTE IMMEDIATE 'ALTER TABLE OPS_SERVICE_ORDER ADD (FEEDBACK_COMMENT VARCHAR2(512))';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -1430 THEN RAISE; END IF; END;
/
BEGIN
  EXECUTE IMMEDIATE 'ALTER TABLE OPS_SERVICE_ORDER ADD (ALERT_ID NUMBER)';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -1430 THEN RAISE; END IF; END;
/

-- ============================================================
-- 3. 工单评论/流转记录表
-- ============================================================
BEGIN
  EXECUTE IMMEDIATE '
    CREATE TABLE OPS_ORDER_COMMENT (
      COMMENT_ID   NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
      ORDER_ID     NUMBER        NOT NULL,
      COMMENT_TYPE VARCHAR2(16)  DEFAULT ''COMMENT'',
      CONTENT      VARCHAR2(1024),
      CREATED_BY   NUMBER,
      CREATED_AT   TIMESTAMP     DEFAULT SYSTIMESTAMP
    )';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -955 THEN RAISE; END IF; END;
/

COMMENT ON TABLE OPS_ORDER_COMMENT IS 'F-50 工单评论与流转记录';
COMMENT ON COLUMN OPS_ORDER_COMMENT.COMMENT_TYPE IS 'COMMENT/STATUS_CHANGE/ASSIGN';

-- 索引
CREATE INDEX IDX_ORDER_COMMENT ON OPS_ORDER_COMMENT(ORDER_ID, CREATED_AT);

-- ============================================================
-- 4. 种子数据 — 服务目录
-- ============================================================
MERGE INTO OPS_SERVICE_CATALOG t
USING (SELECT '实例扩容申请' AS SERVICE_NAME FROM DUAL) s
ON (t.SERVICE_NAME = s.SERVICE_NAME)
WHEN NOT MATCHED THEN INSERT (SERVICE_NAME, CATEGORY, DESCRIPTION, NEED_APPROVAL, ICON, SORT_ORDER, ENABLED, SLA_HOURS, ASSIGNEE_ROLE)
  VALUES ('实例扩容申请', 'CAPACITY', 'CPU/内存/存储扩容工单', 1, 'Expand', 10, 1, 48, 'DBA');

MERGE INTO OPS_SERVICE_CATALOG t
USING (SELECT '权限申请' AS SERVICE_NAME FROM DUAL) s
ON (t.SERVICE_NAME = s.SERVICE_NAME)
WHEN NOT MATCHED THEN INSERT (SERVICE_NAME, CATEGORY, DESCRIPTION, NEED_APPROVAL, ICON, SORT_ORDER, ENABLED, SLA_HOURS, ASSIGNEE_ROLE)
  VALUES ('权限申请', 'ACCESS', '数据库账号权限开通/变更', 1, 'Lock', 20, 1, 24, 'DBA');

MERGE INTO OPS_SERVICE_CATALOG t
USING (SELECT '数据导出' AS SERVICE_NAME FROM DUAL) s
ON (t.SERVICE_NAME = s.SERVICE_NAME)
WHEN NOT MATCHED THEN INSERT (SERVICE_NAME, CATEGORY, DESCRIPTION, NEED_APPROVAL, ICON, SORT_ORDER, ENABLED, SLA_HOURS, ASSIGNEE_ROLE)
  VALUES ('数据导出', 'DATA', '数据导出/迁移/清洗请求', 1, 'Download', 30, 1, 72, 'DBA');

MERGE INTO OPS_SERVICE_CATALOG t
USING (SELECT '参数变更' AS SERVICE_NAME FROM DUAL) s
ON (t.SERVICE_NAME = s.SERVICE_NAME)
WHEN NOT MATCHED THEN INSERT (SERVICE_NAME, CATEGORY, DESCRIPTION, NEED_APPROVAL, ICON, SORT_ORDER, ENABLED, SLA_HOURS, ASSIGNEE_ROLE)
  VALUES ('参数变更', 'CONFIG', '数据库参数调整', 1, 'Setting', 40, 1, 24, 'DBA');

MERGE INTO OPS_SERVICE_CATALOG t
USING (SELECT '故障处理' AS SERVICE_NAME FROM DUAL) s
ON (t.SERVICE_NAME = s.SERVICE_NAME)
WHEN NOT MATCHED THEN INSERT (SERVICE_NAME, CATEGORY, DESCRIPTION, NEED_APPROVAL, ICON, SORT_ORDER, ENABLED, SLA_HOURS, ASSIGNEE_ROLE)
  VALUES ('故障处理', 'INCIDENT', '数据库故障排查与处理', 0, 'Warning', 50, 1, 4, 'DBA');

MERGE INTO OPS_SERVICE_CATALOG t
USING (SELECT '巡检报告' AS SERVICE_NAME FROM DUAL) s
ON (t.SERVICE_NAME = s.SERVICE_NAME)
WHEN NOT MATCHED THEN INSERT (SERVICE_NAME, CATEGORY, DESCRIPTION, NEED_APPROVAL, ICON, SORT_ORDER, ENABLED, SLA_HOURS, ASSIGNEE_ROLE)
  VALUES ('巡检报告', 'REPORT', '定期巡检报告生成与解读', 0, 'Document', 60, 1, 48, 'OPS');

-- ============================================================
-- 5. 菜单注册
-- ============================================================
MERGE INTO SYS_MENU t
USING (SELECT '/service-catalog' AS p FROM DUAL) s ON (t.MENU_PATH = s.p)
WHEN NOT MATCHED THEN INSERT (MENU_PATH, MENU_NAME, SORT_ORDER)
  VALUES ('/service-catalog', '服务工单', 65);

-- 授权 ADMIN/DBA/OPS/DEV/REVIEWER
INSERT INTO SYS_ROLE_MENU (ROLE_ID, MENU_ID)
SELECT r.ROLE_ID, m.MENU_ID
FROM SYS_ROLE r, SYS_MENU m
WHERE r.ROLE_CODE IN ('ADMIN', 'DBA', 'OPS', 'DEV', 'REVIEWER')
  AND m.MENU_PATH = '/service-catalog'
  AND NOT EXISTS (
    SELECT 1 FROM SYS_ROLE_MENU rm WHERE rm.ROLE_ID = r.ROLE_ID AND rm.MENU_ID = m.MENU_ID
  );

COMMIT;
