-- ============================================================
-- F-18 告警静默 — 维护窗口配置表
-- ============================================================

-- 告警静默规则
CREATE TABLE ALERT_SILENCE_RULE (
  RULE_ID         NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  RULE_NAME       VARCHAR2(128) NOT NULL,
  DESCRIPTION     VARCHAR2(512),
  -- 匹配条件（NULL=全部匹配）
  INSTANCE_ID     NUMBER,               -- 绑定实例，NULL=所有实例
  SEVERITY        VARCHAR2(64),         -- 逗号分隔级别，NULL=所有级别
  RULE_NAME_MATCH VARCHAR2(128),        -- 告警规则名匹配，NULL=所有规则
  -- 静默时间窗口
  SILENCE_TYPE    VARCHAR2(16) DEFAULT 'ONCE',  -- ONCE=一次性 / RECURRING=周期性
  -- 一次性静默
  START_TIME      TIMESTAMP,            -- 开始时间（ONCE 类型必填）
  END_TIME        TIMESTAMP,            -- 结束时间（ONCE 类型必填）
  -- 周期性静默
  CRON_EXPR       VARCHAR2(128),        -- cron 表达式，如 "0 2 * * 1-5"（工作日2点）
  DURATION_MIN    NUMBER,               -- 持续分钟数（RECURRING 类型必填）
  TIMEZONE        VARCHAR2(64) DEFAULT 'Asia/Shanghai',
  -- 状态
  ENABLED         NUMBER(1) DEFAULT 1,
  CREATED_BY      VARCHAR2(64),
  CREATED_AT      TIMESTAMP DEFAULT SYSTIMESTAMP,
  UPDATED_AT      TIMESTAMP DEFAULT SYSTIMESTAMP
);

COMMENT ON TABLE  ALERT_SILENCE_RULE IS 'F-18 告警静默规则（维护窗口配置）';
COMMENT ON COLUMN ALERT_SILENCE_RULE.SILENCE_TYPE IS 'ONCE=一次性/RECURRING=周期性';
COMMENT ON COLUMN ALERT_SILENCE_RULE.CRON_EXPR IS '周期性静默的cron表达式';
COMMENT ON COLUMN ALERT_SILENCE_RULE.DURATION_MIN IS '周期性静默持续分钟数';

-- 静默记录（记录哪些告警被静默了）
CREATE TABLE ALERT_SILENCE_LOG (
  LOG_ID          NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  RULE_ID         NUMBER NOT NULL,
  ALERT_ID        NUMBER NOT NULL,
  SILENCED_AT     TIMESTAMP DEFAULT SYSTIMESTAMP,
  SILENCE_REASON  VARCHAR2(256),        -- 静默原因说明
  CONSTRAINT FK_SILENCE_LOG_RULE FOREIGN KEY (RULE_ID)
    REFERENCES ALERT_SILENCE_RULE(RULE_ID),
  CONSTRAINT FK_SILENCE_LOG_ALERT FOREIGN KEY (ALERT_ID)
    REFERENCES ALERT_RECORD(ALERT_ID)
);

COMMENT ON TABLE ALERT_SILENCE_LOG IS 'F-18 告警静默记录';

CREATE INDEX IDX_SILENCE_LOG_ALERT ON ALERT_SILENCE_LOG(ALERT_ID);
CREATE INDEX IDX_SILENCE_LOG_RULE ON ALERT_SILENCE_LOG(RULE_ID);

-- 给 ALERT_RECORD 增加静默字段
ALTER TABLE ALERT_RECORD ADD (SILENCE_RULE_ID NUMBER);
ALTER TABLE ALERT_RECORD ADD (SILENCED_AT TIMESTAMP);

COMMENT ON COLUMN ALERT_RECORD.SILENCE_RULE_ID IS 'F-18 触发静默的规则ID';
COMMENT ON COLUMN ALERT_RECORD.SILENCED_AT IS 'F-18 被静默的时间';

-- 添加 STATUS 的新值说明
COMMENT ON COLUMN ALERT_RECORD.STATUS IS 'OPEN/ACKNOWLEDGED/RESOLVED/SUPPRESSED/SILENCED';

COMMIT;
