-- §5.7 自动化运维表结构增量（在已执行过旧版 init.sql 的库上手工执行一次）
-- 若某表已存在会报错，可忽略对应段落。

ALTER TABLE INSPECT_RESULT ADD (BATCH_ID NUMBER);

-- 以下与 backend/sql/init.sql 中 §5.7 段落一致；按需复制执行或整段执行。

CREATE TABLE DEPLOY_TEMPLATE (
  TEMPLATE_ID   NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  TEMPLATE_NAME VARCHAR2(128) NOT NULL,
  DEPLOY_MODE   VARCHAR2(32)  NOT NULL,
  DESCRIPTION   VARCHAR2(512),
  PARAM_SCHEMA  CLOB,
  ENABLED       NUMBER(1) DEFAULT 1,
  CREATED_AT    TIMESTAMP DEFAULT SYSTIMESTAMP,
  UPDATED_AT    TIMESTAMP DEFAULT SYSTIMESTAMP
);

CREATE TABLE DEPLOY_JOB (
  JOB_ID       NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  TEMPLATE_ID  NUMBER,
  INSTANCE_ID  NUMBER,
  STATUS       VARCHAR2(32) DEFAULT 'PENDING',
  PARAMS       CLOB,
  LOG_SUMMARY  VARCHAR2(2000),
  CREATED_BY   NUMBER,
  START_TIME   TIMESTAMP,
  END_TIME     TIMESTAMP,
  CREATED_AT   TIMESTAMP DEFAULT SYSTIMESTAMP
);

CREATE TABLE HA_SWITCH_PLAN (
  PLAN_ID              NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  PLAN_NAME            VARCHAR2(128) NOT NULL,
  PRIMARY_INSTANCE_ID  NUMBER,
  STANDBY_INSTANCE_ID  NUMBER,
  EVAL_RESULT          CLOB,
  STATUS               VARCHAR2(32) DEFAULT 'DRAFT',
  CREATED_AT           TIMESTAMP DEFAULT SYSTIMESTAMP
);

CREATE TABLE HA_SWITCH_AUDIT (
  AUDIT_ID      NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  PLAN_ID       NUMBER NOT NULL,
  ACTION_TYPE   VARCHAR2(64) NOT NULL,
  RESULT_STATUS VARCHAR2(32),
  DETAIL        CLOB,
  OPERATED_BY   VARCHAR2(64),
  CREATED_AT    TIMESTAMP DEFAULT SYSTIMESTAMP
);

CREATE TABLE RUNBOOK_DEF (
  RUNBOOK_ID    NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  RUNBOOK_NAME  VARCHAR2(128) NOT NULL,
  VERSION_NUM   NUMBER DEFAULT 1,
  DAG_JSON      CLOB,
  TRIGGER_ALERT NUMBER(1) DEFAULT 0,
  ENABLED       NUMBER(1) DEFAULT 1,
  CREATED_AT    TIMESTAMP DEFAULT SYSTIMESTAMP
);

CREATE TABLE RUNBOOK_EXEC_LOG (
  EXEC_ID       NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  RUNBOOK_ID    NUMBER NOT NULL,
  INSTANCE_ID   NUMBER,
  TRIGGER_TYPE  VARCHAR2(32) DEFAULT 'MANUAL',
  STATUS        VARCHAR2(32) DEFAULT 'PENDING',
  NODE_LOG      CLOB,
  START_TIME    TIMESTAMP,
  END_TIME      TIMESTAMP,
  CREATED_BY    NUMBER,
  CREATED_AT    TIMESTAMP DEFAULT SYSTIMESTAMP
);

CREATE TABLE SELF_HEAL_POLICY (
  POLICY_ID      NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  POLICY_NAME    VARCHAR2(128) NOT NULL,
  INSTANCE_ID    NUMBER,
  RULE_TYPE      VARCHAR2(64),
  CONDITION_JSON CLOB,
  ACTION_MODE    VARCHAR2(32) DEFAULT 'ALERT_ONLY',
  ENABLED        NUMBER(1) DEFAULT 1,
  CREATED_AT     TIMESTAMP DEFAULT SYSTIMESTAMP
);

CREATE TABLE OPS_SERVICE_CATALOG (
  CATALOG_ID    NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  SERVICE_NAME  VARCHAR2(128) NOT NULL,
  CATEGORY      VARCHAR2(64),
  DESCRIPTION   VARCHAR2(512),
  NEED_APPROVAL NUMBER(1) DEFAULT 1,
  CREATED_AT    TIMESTAMP DEFAULT SYSTIMESTAMP
);

CREATE TABLE OPS_SERVICE_ORDER (
  ORDER_ID      NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  CATALOG_ID    NUMBER,
  INSTANCE_ID   NUMBER,
  STATUS        VARCHAR2(32) DEFAULT 'OPEN',
  TICKET_REF    VARCHAR2(128),
  REMARK        VARCHAR2(512),
  CREATED_BY    NUMBER,
  CREATED_AT    TIMESTAMP DEFAULT SYSTIMESTAMP
);

CREATE TABLE SPACE_POLICY (
  SPACE_POLICY_ID NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  INSTANCE_ID     NUMBER,
  THRESHOLD_PCT   NUMBER DEFAULT 85,
  CLEAN_TMP       NUMBER(1) DEFAULT 0,
  SCHEDULE_CRON   VARCHAR2(64),
  ENABLED         NUMBER(1) DEFAULT 1,
  CREATED_AT      TIMESTAMP DEFAULT SYSTIMESTAMP
);

CREATE TABLE SCRIPT_REPO (
  SCRIPT_ID       NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  SCRIPT_NAME     VARCHAR2(128) NOT NULL,
  LANG            VARCHAR2(16) DEFAULT 'SHELL',
  CONTENT         CLOB,
  VERSION_NUM     NUMBER DEFAULT 1,
  APPROVAL_STATUS VARCHAR2(32) DEFAULT 'DRAFT',
  CREATED_BY      NUMBER,
  CREATED_AT      TIMESTAMP DEFAULT SYSTIMESTAMP
);

CREATE TABLE SCRIPT_EXEC_LOG (
  EXEC_ID        NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  SCRIPT_ID      NUMBER,
  INSTANCE_ID    NUMBER,
  STATUS         VARCHAR2(32),
  EXIT_CODE      NUMBER,
  OUTPUT_SUMMARY VARCHAR2(2000),
  CREATED_BY     NUMBER,
  CREATED_AT     TIMESTAMP DEFAULT SYSTIMESTAMP
);

CREATE TABLE AUTOMATION_INSPECT_BATCH (
  BATCH_ID     NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  BATCH_NAME   VARCHAR2(128),
  INSTANCE_IDS VARCHAR2(2000),
  CRON_EXPR    VARCHAR2(64),
  STATUS       VARCHAR2(32) DEFAULT 'IDLE',
  LAST_RUN_AT  TIMESTAMP,
  CREATED_AT   TIMESTAMP DEFAULT SYSTIMESTAMP
);

CREATE TABLE AUTOMATION_EXEC_LOG (
  EXEC_ID    NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  CATEGORY   VARCHAR2(32),
  REF_ID     NUMBER,
  ACTION     VARCHAR2(128),
  STATUS     VARCHAR2(32),
  MESSAGE    VARCHAR2(2000),
  CREATED_BY NUMBER,
  CREATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP
);

CREATE INDEX IDX_INSPECT_BATCH ON INSPECT_RESULT(BATCH_ID);
CREATE INDEX IDX_DEPLOY_JOB_TPL ON DEPLOY_JOB(TEMPLATE_ID);
CREATE INDEX IDX_HA_AUDIT_PLAN ON HA_SWITCH_AUDIT(PLAN_ID);
CREATE INDEX IDX_RB_EXEC_RB ON RUNBOOK_EXEC_LOG(RUNBOOK_ID);
CREATE INDEX IDX_BACKUP_REC_INST ON BACKUP_RECORD(INSTANCE_ID, START_TIME DESC);

CREATE TABLE INSPECT_CHECKV8_REPORT (
  REPORT_ID      NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  INSTANCE_ID    NUMBER NOT NULL,
  BATCH_ID       NUMBER,
  OVERALL_SCORE  NUMBER(3),
  OVERALL_STATUS VARCHAR2(16),
  SUMMARY        VARCHAR2(4000),
  PAYLOAD        CLOB,
  CREATED_BY     NUMBER,
  CREATED_AT     TIMESTAMP DEFAULT SYSTIMESTAMP
);

CREATE INDEX IDX_CHK8_INST ON INSPECT_CHECKV8_REPORT(INSTANCE_ID, CREATED_AT DESC);
CREATE INDEX IDX_CHK8_BATCH ON INSPECT_CHECKV8_REPORT(BATCH_ID);

COMMIT;
