-- F-69 系统配置：全局参数可视化管理
-- 创建 SYS_CONFIG 表，存储平台可配置参数

BEGIN
  EXECUTE IMMEDIATE '
    CREATE TABLE SYS_CONFIG (
      CONFIG_ID     NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
      CONFIG_KEY    VARCHAR2(128) NOT NULL UNIQUE,
      CONFIG_VALUE  VARCHAR2(512),
      DEFAULT_VALUE VARCHAR2(512),
      CATEGORY      VARCHAR2(64),
      LABEL         VARCHAR2(128),
      DESCRIPTION   VARCHAR2(512),
      VALUE_TYPE    VARCHAR2(16) DEFAULT ''NUMBER'',
      MIN_VAL       NUMBER,
      MAX_VAL       NUMBER,
      OPTIONS       VARCHAR2(1024),
      UPDATED_BY    NUMBER,
      UPDATED_AT    TIMESTAMP DEFAULT SYSTIMESTAMP
    )';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -955 THEN RAISE; END IF; END;
/

COMMENT ON TABLE SYS_CONFIG IS 'F-69 系统全局配置参数';
COMMENT ON COLUMN SYS_CONFIG.VALUE_TYPE IS 'NUMBER/STRING/BOOLEAN/SELECT';

-- 种子数据：采集频率
MERGE INTO SYS_CONFIG t USING (SELECT 'monitor.collect.interval_ms' AS k FROM DUAL) s
ON (t.CONFIG_KEY = s.k)
WHEN NOT MATCHED THEN INSERT (CONFIG_KEY, CONFIG_VALUE, DEFAULT_VALUE, CATEGORY, LABEL, DESCRIPTION, VALUE_TYPE, MIN_VAL, MAX_VAL)
  VALUES ('monitor.collect.interval_ms', '90000', '90000', '采集频率', '监控采集间隔(ms)', '周期性采集监控指标的时间间隔，最小60000ms', 'NUMBER', 60000, 3600000);

MERGE INTO SYS_CONFIG t USING (SELECT 'monitor.collect.first_delay_ms' AS k FROM DUAL) s
ON (t.CONFIG_KEY = s.k)
WHEN NOT MATCHED THEN INSERT (CONFIG_KEY, CONFIG_VALUE, DEFAULT_VALUE, CATEGORY, LABEL, DESCRIPTION, VALUE_TYPE, MIN_VAL, MAX_VAL)
  VALUES ('monitor.collect.first_delay_ms', '8000', '8000', '采集频率', '首次采集延迟(ms)', '服务启动后首次采集的延迟时间', 'NUMBER', 1000, 60000);

-- 种子数据：告警延迟
MERGE INTO SYS_CONFIG t USING (SELECT 'alert.evaluation.default_duration_min' AS k FROM DUAL) s
ON (t.CONFIG_KEY = s.k)
WHEN NOT MATCHED THEN INSERT (CONFIG_KEY, CONFIG_VALUE, DEFAULT_VALUE, CATEGORY, LABEL, DESCRIPTION, VALUE_TYPE, MIN_VAL, MAX_VAL)
  VALUES ('alert.evaluation.default_duration_min', '5', '5', '告警延迟', '默认持续时长(分钟)', '告警规则触发前条件需持续满足的默认分钟数', 'NUMBER', 1, 60);

MERGE INTO SYS_CONFIG t USING (SELECT 'alert.aggregation.window_min' AS k FROM DUAL) s
ON (t.CONFIG_KEY = s.k)
WHEN NOT MATCHED THEN INSERT (CONFIG_KEY, CONFIG_VALUE, DEFAULT_VALUE, CATEGORY, LABEL, DESCRIPTION, VALUE_TYPE, MIN_VAL, MAX_VAL)
  VALUES ('alert.aggregation.window_min', '10', '10', '告警延迟', '聚合窗口(分钟)', '告警聚合去重的时间窗口', 'NUMBER', 1, 60);

MERGE INTO SYS_CONFIG t USING (SELECT 'alert.suppression.default_window_min' AS k FROM DUAL) s
ON (t.CONFIG_KEY = s.k)
WHEN NOT MATCHED THEN INSERT (CONFIG_KEY, CONFIG_VALUE, DEFAULT_VALUE, CATEGORY, LABEL, DESCRIPTION, VALUE_TYPE, MIN_VAL, MAX_VAL)
  VALUES ('alert.suppression.default_window_min', '60', '60', '告警延迟', '默认抑制窗口(分钟)', '告警抑制规则的默认时间窗口', 'NUMBER', 5, 1440);

-- 种子数据：保留策略
MERGE INTO SYS_CONFIG t USING (SELECT 'retention.metric_sample_days' AS k FROM DUAL) s
ON (t.CONFIG_KEY = s.k)
WHEN NOT MATCHED THEN INSERT (CONFIG_KEY, CONFIG_VALUE, DEFAULT_VALUE, CATEGORY, LABEL, DESCRIPTION, VALUE_TYPE, MIN_VAL, MAX_VAL)
  VALUES ('retention.metric_sample_days', '8', '8', '保留策略', '监控样本保留(天)', 'MONITOR_METRIC_SAMPLE 数据保留天数', 'NUMBER', 1, 365);

MERGE INTO SYS_CONFIG t USING (SELECT 'retention.alert_record_days' AS k FROM DUAL) s
ON (t.CONFIG_KEY = s.k)
WHEN NOT MATCHED THEN INSERT (CONFIG_KEY, CONFIG_VALUE, DEFAULT_VALUE, CATEGORY, LABEL, DESCRIPTION, VALUE_TYPE, MIN_VAL, MAX_VAL)
  VALUES ('retention.alert_record_days', '90', '90', '保留策略', '告警记录保留(天)', 'ALERT_RECORD 已关闭告警保留天数（0=永久）', 'NUMBER', 0, 365);

MERGE INTO SYS_CONFIG t USING (SELECT 'retention.audit_log_days' AS k FROM DUAL) s
ON (t.CONFIG_KEY = s.k)
WHEN NOT MATCHED THEN INSERT (CONFIG_KEY, CONFIG_VALUE, DEFAULT_VALUE, CATEGORY, LABEL, DESCRIPTION, VALUE_TYPE, MIN_VAL, MAX_VAL)
  VALUES ('retention.audit_log_days', '180', '180', '保留策略', '审计日志保留(天)', 'SYS_AUDIT_LOG 保留天数（0=永久）', 'NUMBER', 0, 365);

MERGE INTO SYS_CONFIG t USING (SELECT 'retention.sql_history_days' AS k FROM DUAL) s
ON (t.CONFIG_KEY = s.k)
WHEN NOT MATCHED THEN INSERT (CONFIG_KEY, CONFIG_VALUE, DEFAULT_VALUE, CATEGORY, LABEL, DESCRIPTION, VALUE_TYPE, MIN_VAL, MAX_VAL)
  VALUES ('retention.sql_history_days', '30', '30', '保留策略', 'SQL历史保留(天)', 'SQL_WORKBENCH_HISTORY 保留天数', 'NUMBER', 1, 365);

-- 种子数据：连接池
MERGE INTO SYS_CONFIG t USING (SELECT 'db.pool.max' AS k FROM DUAL) s
ON (t.CONFIG_KEY = s.k)
WHEN NOT MATCHED THEN INSERT (CONFIG_KEY, CONFIG_VALUE, DEFAULT_VALUE, CATEGORY, LABEL, DESCRIPTION, VALUE_TYPE, MIN_VAL, MAX_VAL)
  VALUES ('db.pool.max', '20', '20', '连接池', '最大连接数', 'Oracle 连接池最大连接数', 'NUMBER', 2, 100);

MERGE INTO SYS_CONFIG t USING (SELECT 'db.pool.min' AS k FROM DUAL) s
ON (t.CONFIG_KEY = s.k)
WHEN NOT MATCHED THEN INSERT (CONFIG_KEY, CONFIG_VALUE, DEFAULT_VALUE, CATEGORY, LABEL, DESCRIPTION, VALUE_TYPE, MIN_VAL, MAX_VAL)
  VALUES ('db.pool.min', '2', '2', '连接池', '最小连接数', 'Oracle 连接池最小连接数', 'NUMBER', 1, 50);

MERGE INTO SYS_CONFIG t USING (SELECT 'db.pool.timeout_sec' AS k FROM DUAL) s
ON (t.CONFIG_KEY = s.k)
WHEN NOT MATCHED THEN INSERT (CONFIG_KEY, CONFIG_VALUE, DEFAULT_VALUE, CATEGORY, LABEL, DESCRIPTION, VALUE_TYPE, MIN_VAL, MAX_VAL)
  VALUES ('db.pool.timeout_sec', '60', '60', '连接池', '连接超时(秒)', '空闲连接回收超时时间', 'NUMBER', 10, 600);

-- 菜单注册
MERGE INTO SYS_MENU t
USING (SELECT '/settings/system-config' AS p FROM DUAL) s ON (t.MENU_PATH = s.p)
WHEN NOT MATCHED THEN INSERT (MENU_PATH, MENU_NAME, SORT_ORDER)
  VALUES ('/settings/system-config', '系统配置', 115);

INSERT INTO SYS_ROLE_MENU (ROLE_ID, MENU_ID)
SELECT r.ROLE_ID, m.MENU_ID
FROM SYS_ROLE r, SYS_MENU m
WHERE r.ROLE_CODE IN ('ADMIN', 'DBA')
  AND m.MENU_PATH = '/settings/system-config'
  AND NOT EXISTS (
    SELECT 1 FROM SYS_ROLE_MENU rm WHERE rm.ROLE_ID = r.ROLE_ID AND rm.MENU_ID = m.MENU_ID
  );

COMMIT;
