-- Migration: F-38 SQL Review (SQL评审)
-- Creates SQL_REVIEW_TICKET and SQL_REVIEW_COMMENT tables
-- Supports: online/offline/self review workflow with multi-stage approval

-- 1. SQL 评审工单表
CREATE TABLE SQL_REVIEW_TICKET (
  TICKET_ID       NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  TITLE           VARCHAR2(256) NOT NULL,           -- 评审标题
  SQL_TEXT        CLOB         NOT NULL,            -- 待评审 SQL
  SQL_HASH        VARCHAR2(64),                     -- SQL MD5 哈希
  INSTANCE_ID     NUMBER,                           -- 目标实例
  DB_TYPE         VARCHAR2(32),                     -- ORACLE/MYSQL/POSTGRESQL
  ENVIRONMENT     VARCHAR2(32)  DEFAULT 'DEV',      -- DEV/STAGING/PROD
  SOURCE          VARCHAR2(32)  DEFAULT 'ONLINE',   -- ONLINE/OFFLINE/SELF
  -- ONLINE: 在线提交，自动触发审核
  -- OFFLINE: 离线批量提交，人工排队审核
  -- SELF: 自助评审，开发自测后提交
  STATUS          VARCHAR2(32)  DEFAULT 'PENDING',  -- PENDING/IN_REVIEW/APPROVED/REJECTED/CHANGES_REQUESTED/CANCELLED
  AUDIT_ID        NUMBER,                           -- 关联的自动审核记录 ID
  SCORE           NUMBER(5,1),                      -- 自动审核评分
  RISK_LEVEL      VARCHAR2(16),                     -- LOW/MEDIUM/HIGH/CRITICAL
  PRIORITY        VARCHAR2(16)  DEFAULT 'NORMAL',   -- LOW/NORMAL/HIGH/URGENT
  SUBMITTED_BY    NUMBER        NOT NULL,           -- 提交人 USER_ID
  ASSIGNED_TO     NUMBER,                           -- 指定审核人 USER_ID
  REVIEWED_BY     NUMBER,                           -- 实际审核人 USER_ID
  REVIEW_COMMENT  VARCHAR2(2000),                   -- 审核意见
  SUBMITTED_AT    TIMESTAMP     DEFAULT SYSTIMESTAMP,
  REVIEWED_AT     TIMESTAMP,
  EXECUTED_AT     TIMESTAMP,                        -- 执行时间（审核通过后）
  TENANT_ID       NUMBER        DEFAULT 1,
  CREATED_AT      TIMESTAMP     DEFAULT SYSTIMESTAMP,
  UPDATED_AT      TIMESTAMP     DEFAULT SYSTIMESTAMP
);
COMMENT ON TABLE SQL_REVIEW_TICKET IS 'SQL 评审工单（F-38 在线/离线/自助评审流程）';
COMMENT ON COLUMN SQL_REVIEW_TICKET.SOURCE IS 'ONLINE在线评审/OFFLINE离线批量/SELF自助评审';
COMMENT ON COLUMN SQL_REVIEW_TICKET.STATUS IS 'PENDING待审核/IN_REVIEW审核中/APPROVED已通过/REJECTED已拒绝/CHANGES_REQUESTED需修改/CANCELLED已取消';
CREATE INDEX IDX_SRT_STATUS ON SQL_REVIEW_TICKET(STATUS);
CREATE INDEX IDX_SRT_SUBMITTER ON SQL_REVIEW_TICKET(SUBMITTED_BY);
CREATE INDEX IDX_SRT_ASSIGNED ON SQL_REVIEW_TICKET(ASSIGNED_TO);
CREATE INDEX IDX_SRT_HASH ON SQL_REVIEW_TICKET(SQL_HASH);

-- 2. SQL 评审评论表
CREATE TABLE SQL_REVIEW_COMMENT (
  COMMENT_ID      NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  TICKET_ID       NUMBER        NOT NULL,
  USER_ID         NUMBER        NOT NULL,           -- 评论人
  COMMENT_TEXT    VARCHAR2(2000) NOT NULL,
  COMMENT_TYPE    VARCHAR2(32)  DEFAULT 'COMMENT',  -- COMMENT/APPROVE/REJECT/REQUEST_CHANGE/SYSTEM
  -- COMMENT: 普通评论
  -- APPROVE: 审核通过
  -- REJECT: 审核拒绝
  -- REQUEST_CHANGE: 要求修改
  -- SYSTEM: 系统自动消息（如自动审核结果）
  CREATED_AT      TIMESTAMP     DEFAULT SYSTIMESTAMP,
  CONSTRAINT FK_SRC_TICKET FOREIGN KEY (TICKET_ID) REFERENCES SQL_REVIEW_TICKET(TICKET_ID) ON DELETE CASCADE
);
COMMENT ON TABLE SQL_REVIEW_COMMENT IS 'SQL 评审评论/审核记录';
CREATE INDEX IDX_SRC_TICKET ON SQL_REVIEW_COMMENT(TICKET_ID);

-- 3. 菜单项：SQL 评审
MERGE INTO SYS_MENU t
USING (SELECT '/sql-review' AS p FROM DUAL) s ON (t.MENU_PATH = s.p)
WHEN NOT MATCHED THEN INSERT (MENU_PATH, MENU_NAME, SORT_ORDER) VALUES ('/sql-review', 'SQL评审', 32);

-- 4. 授权 ADMIN/DBA/OPS/DEV
INSERT INTO SYS_ROLE_MENU (ROLE_ID, MENU_ID)
SELECT r.ROLE_ID, m.MENU_ID
FROM SYS_ROLE r, SYS_MENU m
WHERE r.ROLE_CODE IN ('ADMIN', 'DBA', 'OPS', 'DEV') AND m.MENU_PATH = '/sql-review'
  AND NOT EXISTS (SELECT 1 FROM SYS_ROLE_MENU rm WHERE rm.ROLE_ID = r.ROLE_ID AND rm.MENU_ID = m.MENU_ID);

COMMIT;
