-- SQL 优化 Agent 专用知识库（向量块存 Oracle，与平台通用 AI_KB_CHUNK 分离）
-- 执行前请确认目标用户具备 CREATE TABLE 权限
-- 启用检索：在 sql-optimizer-agent 运行环境中设置 SQL_OPT_VECTOR_BACKEND=oracle
-- （默认 none 不访问本表；备选 milvus / pgvector 见 sql_opt_retriever.py 预留实现）

-- 文档元数据（可选：多块归属同一文档）
CREATE TABLE SQL_OPT_KB_DOC (
  DOC_ID         NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  TITLE          VARCHAR2(512) NOT NULL,
  SOURCE         VARCHAR2(256),
  ENABLED        NUMBER(1) DEFAULT 1,
  CREATED_AT     TIMESTAMP DEFAULT SYSTIMESTAMP
);

COMMENT ON TABLE SQL_OPT_KB_DOC IS 'SQL优化Agent知识库-文档头（仅服务SQL优化RAG）';

-- 分块 + Embedding（JSON 数组）+ 方言过滤
CREATE TABLE SQL_OPT_KB_CHUNK (
  CHUNK_ID       NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  DOC_ID         NUMBER NOT NULL,
  CHUNK_INDEX    NUMBER NOT NULL,
  CHUNK_TEXT     CLOB NOT NULL,
  EMBEDDING      CLOB,
  EMBEDDING_DIM  NUMBER DEFAULT 0,
  DB_TYPE        VARCHAR2(32),
  KEYWORD_HASH   VARCHAR2(256),
  CREATED_AT     TIMESTAMP DEFAULT SYSTIMESTAMP,
  CONSTRAINT FK_SQL_OPT_CHUNK_DOC FOREIGN KEY (DOC_ID) REFERENCES SQL_OPT_KB_DOC(DOC_ID)
);

COMMENT ON TABLE SQL_OPT_KB_CHUNK IS 'SQL优化Agent知识库-分块向量（EMBEDDING为JSON；DB_TYPE: ORACLE/POSTGRESQL/MYSQL/ALL）';
COMMENT ON COLUMN SQL_OPT_KB_CHUNK.DB_TYPE IS '目标方言：与待优化SQL一致时优先命中；ALL 表示通用';
COMMENT ON COLUMN SQL_OPT_KB_CHUNK.KEYWORD_HASH IS '关键词摘要，便于后续扩展混合检索';

CREATE INDEX IDX_SQL_OPT_CHUNK_DOC ON SQL_OPT_KB_CHUNK(DOC_ID, CHUNK_INDEX);
CREATE INDEX IDX_SQL_OPT_CHUNK_DB ON SQL_OPT_KB_CHUNK(DB_TYPE);

-- 写入示例（需应用侧先对 CHUNK_TEXT 调 Ollama /api/embeddings 得到 JSON 数组再插入）：
-- INSERT INTO SQL_OPT_KB_DOC (TITLE, SOURCE, ENABLED) VALUES ('Oracle 索引与全表扫描', 'manual', 1);
-- INSERT INTO SQL_OPT_KB_CHUNK (DOC_ID, CHUNK_INDEX, CHUNK_TEXT, EMBEDDING, EMBEDDING_DIM, DB_TYPE, KEYWORD_HASH)
-- VALUES (1, 0, '...', '[...]', 768, 'ORACLE', '索引,全表扫描');
