-- Migration: F-03 Cluster Topology Management (集群拓扑管理)
-- Creates CMDB_CLUSTER and CMDB_CLUSTER_MEMBER tables

-- 1. 集群主表
CREATE TABLE CMDB_CLUSTER (
  CLUSTER_ID    NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  CLUSTER_NAME  VARCHAR2(128) NOT NULL,
  CLUSTER_TYPE  VARCHAR2(32)  NOT NULL,  -- RAC/DG/MGR/PXC/PATRONI/REPLICATION/OTHER
  DESCRIPTION   VARCHAR2(512),
  VIP           VARCHAR2(128),
  STATUS        VARCHAR2(16) DEFAULT 'NORMAL',  -- NORMAL/WARNING/ERROR/MAINTENANCE
  TENANT_ID     NUMBER DEFAULT 1,
  CREATED_AT    TIMESTAMP DEFAULT SYSTIMESTAMP,
  UPDATED_AT    TIMESTAMP DEFAULT SYSTIMESTAMP
);
COMMENT ON TABLE CMDB_CLUSTER IS '数据库集群（RAC/DG/MGR/PXC/Patroni等）';

-- 2. 集群成员表
CREATE TABLE CMDB_CLUSTER_MEMBER (
  MEMBER_ID     NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  CLUSTER_ID    NUMBER NOT NULL,
  INSTANCE_ID   NUMBER NOT NULL,
  NODE_ROLE     VARCHAR2(32),  -- PRIMARY/STANDBY/READONLY
  SORT_ORDER    NUMBER DEFAULT 0,
  CREATED_AT    TIMESTAMP DEFAULT SYSTIMESTAMP,
  CONSTRAINT FK_CCM_CLUSTER  FOREIGN KEY (CLUSTER_ID)  REFERENCES CMDB_CLUSTER(CLUSTER_ID) ON DELETE CASCADE,
  CONSTRAINT FK_CCM_INSTANCE FOREIGN KEY (INSTANCE_ID) REFERENCES CMDB_INSTANCE(INSTANCE_ID)
);
COMMENT ON TABLE CMDB_CLUSTER_MEMBER IS '集群成员（实例与集群的关联）';

-- 3. 菜单项
MERGE INTO SYS_MENU t
USING (SELECT '/cmdb/clusters' AS p FROM DUAL) s ON (t.MENU_PATH = s.p)
WHEN NOT MATCHED THEN INSERT (MENU_PATH, MENU_NAME, SORT_ORDER) VALUES ('/cmdb/clusters', '集群拓扑', 56);

-- 4. 授权 ADMIN/DBA
INSERT INTO SYS_ROLE_MENU (ROLE_ID, MENU_ID)
SELECT r.ROLE_ID, m.MENU_ID
FROM SYS_ROLE r, SYS_MENU m
WHERE r.ROLE_CODE = 'ADMIN' AND m.MENU_PATH = '/cmdb/clusters'
  AND NOT EXISTS (SELECT 1 FROM SYS_ROLE_MENU rm WHERE rm.ROLE_ID = r.ROLE_ID AND rm.MENU_ID = m.MENU_ID);

INSERT INTO SYS_ROLE_MENU (ROLE_ID, MENU_ID)
SELECT r.ROLE_ID, m.MENU_ID
FROM SYS_ROLE r, SYS_MENU m
WHERE r.ROLE_CODE = 'DBA' AND m.MENU_PATH = '/cmdb/clusters'
  AND NOT EXISTS (SELECT 1 FROM SYS_ROLE_MENU rm WHERE rm.ROLE_ID = r.ROLE_ID AND rm.MENU_ID = m.MENU_ID);

COMMIT;
