-- ============================================================
-- F-16 告警聚合去重 — 聚合组表
-- ============================================================

-- 告警聚合组
CREATE TABLE ALERT_AGGREGATION (
  AGG_ID            NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  AGG_KEY           VARCHAR2(256) NOT NULL,  -- 聚合键: RULE_NAME|INSTANCE_ID|SEVERITY
  RULE_NAME         VARCHAR2(128),
  INSTANCE_ID       NUMBER,
  INSTANCE_NAME     VARCHAR2(128),
  SEVERITY          VARCHAR2(16),
  REPRESENTATIVE_ID NUMBER,                  -- 代表告警 ID（最早触发的那条）
  ALERT_COUNT       NUMBER DEFAULT 1,        -- 合并的告警总数
  ALERT_IDS         CLOB,                    -- JSON 数组: 所有被合并的告警 ID
  STATUS            VARCHAR2(16) DEFAULT 'ACTIVE', -- ACTIVE/RESOLVED/EXPIRED
  WINDOW_MINUTES    NUMBER DEFAULT 10,       -- 聚合窗口（分钟）
  FIRST_TRIGGER     TIMESTAMP,               -- 组内最早触发时间
  LAST_TRIGGER      TIMESTAMP,               -- 组内最晚触发时间
  CREATED_AT        TIMESTAMP DEFAULT SYSTIMESTAMP,
  UPDATED_AT        TIMESTAMP DEFAULT SYSTIMESTAMP
);

COMMENT ON TABLE  ALERT_AGGREGATION IS 'F-16 告警聚合去重组';
COMMENT ON COLUMN ALERT_AGGREGATION.AGG_KEY IS '聚合键: 规则名|实例ID|严重度 组合';
COMMENT ON COLUMN ALERT_AGGREGATION.REPRESENTATIVE_ID IS '代表告警ID，取组内最早触发的告警';
COMMENT ON COLUMN ALERT_AGGREGATION.ALERT_IDS IS '被合并的告警ID JSON数组';

CREATE INDEX IDX_AGG_KEY ON ALERT_AGGREGATION(AGG_KEY, STATUS);
CREATE INDEX IDX_AGG_INSTANCE ON ALERT_AGGREGATION(INSTANCE_ID, STATUS);
CREATE INDEX IDX_AGG_REPRESENTATIVE ON ALERT_AGGREGATION(REPRESENTATIVE_ID);

-- 给 ALERT_RECORD 增加聚合字段
ALTER TABLE ALERT_RECORD ADD (AGG_GROUP_ID NUMBER);
ALTER TABLE ALERT_RECORD ADD (IS_MERGED NUMBER(1) DEFAULT 0);

COMMENT ON COLUMN ALERT_RECORD.AGG_GROUP_ID IS 'F-16 所属聚合组ID';
COMMENT ON COLUMN ALERT_RECORD.IS_MERGED IS 'F-16 是否被合并(0=否/1=是)';

CREATE INDEX IDX_ALERT_AGG_GROUP ON ALERT_RECORD(AGG_GROUP_ID);

COMMIT;
