-- ============================================================
-- F-10 自定义监控项 — 面板与指标配置表
-- ============================================================

-- 自定义监控面板
CREATE TABLE MONITOR_CUSTOM_PANEL (
  PANEL_ID      NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  PANEL_NAME    VARCHAR2(128) NOT NULL,
  DESCRIPTION   VARCHAR2(512),
  DB_TYPE       VARCHAR2(32),           -- ORACLE/MYSQL/POSTGRESQL/DAMENG/NULL=全部
  LAYOUT_JSON   CLOB,                   -- 布局配置 JSON ({cols, rowHeight})
  ENABLED       NUMBER(1) DEFAULT 1,
  SORT_ORDER    NUMBER   DEFAULT 0,
  CREATED_BY    NUMBER,
  CREATED_AT    TIMESTAMP DEFAULT SYSTIMESTAMP,
  UPDATED_AT    TIMESTAMP DEFAULT SYSTIMESTAMP
);

COMMENT ON TABLE  MONITOR_CUSTOM_PANEL IS 'F-10 自定义监控面板';
COMMENT ON COLUMN MONITOR_CUSTOM_PANEL.DB_TYPE IS '适用数据库类型，NULL=所有类型';
COMMENT ON COLUMN MONITOR_CUSTOM_PANEL.LAYOUT_JSON IS '面板布局配置JSON';

-- 自定义监控指标（面板内的指标项）
CREATE TABLE MONITOR_CUSTOM_METRIC (
  METRIC_ID     NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  PANEL_ID      NUMBER NOT NULL,
  METRIC_NAME   VARCHAR2(128) NOT NULL,
  METRIC_LABEL  VARCHAR2(128),          -- 显示名称
  METRIC_TYPE   VARCHAR2(32) DEFAULT 'SQL', -- SQL/EXPRESSION
  -- SQL 类型指标
  SQL_TEXT      CLOB,                   -- 自定义 SQL（返回单行单列值）
  DB_TYPE       VARCHAR2(32),           -- SQL 适用数据库类型
  -- EXPRESSION 类型指标（基于已有 METRICS_JSON 字段做表达式计算）
  EXPRESSION    CLOB,                   -- 如 avg(METRIC_CPU) 或 last(HEALTH_SCORE)
  INSTANCE_ID   NUMBER,                 -- 绑定实例（EXPRESSION 类型必填）
  -- 展示配置
  CHART_TYPE    VARCHAR2(32) DEFAULT 'gauge', -- gauge/line/bar/number/table
  UNIT          VARCHAR2(32),           -- 单位（%, ms, GB, 个...）
  THRESHOLD_WARN  NUMBER,               -- 告警阈值-警告
  THRESHOLD_CRIT  NUMBER,               -- 告警阈值-严重
  COLOR         VARCHAR2(16),           -- 自定义颜色
  SORT_ORDER    NUMBER DEFAULT 0,
  ENABLED       NUMBER(1) DEFAULT 1,
  CREATED_AT    TIMESTAMP DEFAULT SYSTIMESTAMP,
  CONSTRAINT FK_CUSTOM_METRIC_PANEL FOREIGN KEY (PANEL_ID)
    REFERENCES MONITOR_CUSTOM_PANEL(PANEL_ID) ON DELETE CASCADE
);

COMMENT ON TABLE  MONITOR_CUSTOM_METRIC IS 'F-10 自定义监控指标';
COMMENT ON COLUMN MONITOR_CUSTOM_METRIC.METRIC_TYPE IS 'SQL=自定义SQL查询/EXPRESSION=基于采集指标表达式计算';
COMMENT ON COLUMN MONITOR_CUSTOM_METRIC.SQL_TEXT IS '自定义SQL，需返回单行单列数值';
COMMENT ON COLUMN MONITOR_CUSTOM_METRIC.EXPRESSION IS '表达式如 avg(METRIC_CPU), last(HEALTH_SCORE), max(METRIC_CONN)';
COMMENT ON COLUMN MONITOR_CUSTOM_METRIC.CHART_TYPE IS 'gauge仪表盘/line折线/bar柱状/number数字/table表格';

CREATE INDEX IDX_CUSTOM_METRIC_PANEL ON MONITOR_CUSTOM_METRIC(PANEL_ID, SORT_ORDER);

COMMIT;
