-- Migration: F-17 Alert Suppression (告警抑制)
-- Parent alert suppresses child alerts based on topology, cluster, and severity rules
-- Supports: host→instance, instance→app, cluster primary→member, severity-based suppression

-- 1. 告警抑制规则表
CREATE TABLE ALERT_SUPPRESSION_RULE (
  RULE_ID         NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  RULE_NAME       VARCHAR2(128) NOT NULL,
  RULE_TYPE       VARCHAR2(32)  NOT NULL,          -- TOPOLOGY / CLUSTER / SEVERITY / INSTANCE
  -- TOPOLOGY: host→instance or instance→app (uses CMDB_HOST, CMDB_APP_DB_RELATION)
  -- CLUSTER: cluster primary→standby (uses CMDB_CLUSTER_MEMBER)
  -- SEVERITY: high severity suppresses low severity on same instance
  -- INSTANCE: same instance, any parent alert suppresses child
  DESCRIPTION     VARCHAR2(512),
  PARENT_LEVELS   VARCHAR2(64)  DEFAULT 'P1,P2',   -- 哪些级别的父告警触发抑制（逗号分隔）
  CHILD_LEVELS    VARCHAR2(64)  DEFAULT 'P2,P3,P4', -- 哪些级别的子告警被抑制（逗号分隔）
  SUPPRESS_WINDOW NUMBER        DEFAULT 60,         -- 抑制窗口（分钟），父告警在此时间内有效
  AUTO_RELEASE    NUMBER(1)     DEFAULT 1,          -- 父告警解决后自动解除子告警抑制
  ENABLED         NUMBER(1)     DEFAULT 1,
  TENANT_ID       NUMBER        DEFAULT 1,
  CREATED_BY      VARCHAR2(64),
  CREATED_AT      TIMESTAMP     DEFAULT SYSTIMESTAMP,
  UPDATED_AT      TIMESTAMP     DEFAULT SYSTIMESTAMP
);
COMMENT ON TABLE ALERT_SUPPRESSION_RULE IS '告警抑制规则（父告警抑制子告警的配置）';
COMMENT ON COLUMN ALERT_SUPPRESSION_RULE.RULE_TYPE IS 'TOPOLOGY拓扑级联/CLUSTER集群抑制/SEVERITY级别抑制/INSTANCE同实例抑制';
COMMENT ON COLUMN ALERT_SUPPRESSION_RULE.PARENT_LEVELS IS '触发抑制的父告警级别，逗号分隔';
COMMENT ON COLUMN ALERT_SUPPRESSION_RULE.CHILD_LEVELS IS '被抑制的子告警级别，逗号分隔';

-- 2. 告警抑制记录表
CREATE TABLE ALERT_SUPPRESSION (
  ID              NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  PARENT_ALERT_ID NUMBER NOT NULL,                  -- 父告警 ID
  CHILD_ALERT_ID  NUMBER NOT NULL,                  -- 被抑制的子告警 ID
  RULE_ID         NUMBER,                           -- 命中的抑制规则
  SUPPRESSION_TYPE VARCHAR2(32),                    -- TOPOLOGY / CLUSTER / SEVERITY / INSTANCE
  STATUS          VARCHAR2(16) DEFAULT 'ACTIVE',    -- ACTIVE / RELEASED / EXPIRED
  RELEASED_AT     TIMESTAMP,                        -- 解除时间
  RELEASED_BY     VARCHAR2(64),                     -- 解除人（手动解除时）
  RELEASE_REASON  VARCHAR2(256),                    -- 解除原因
  TENANT_ID       NUMBER DEFAULT 1,
  CREATED_AT      TIMESTAMP DEFAULT SYSTIMESTAMP,
  CONSTRAINT FK_SUP_PARENT FOREIGN KEY (PARENT_ALERT_ID) REFERENCES ALERT_RECORD(ALERT_ID),
  CONSTRAINT FK_SUP_CHILD  FOREIGN KEY (CHILD_ALERT_ID)  REFERENCES ALERT_RECORD(ALERT_ID),
  CONSTRAINT FK_SUP_RULE   FOREIGN KEY (RULE_ID)         REFERENCES ALERT_SUPPRESSION_RULE(RULE_ID)
);
COMMENT ON TABLE ALERT_SUPPRESSION IS '告警抑制记录（记录哪个父告警抑制了哪些子告警）';
CREATE UNIQUE INDEX IDX_SUP_PARENT_CHILD ON ALERT_SUPPRESSION(PARENT_ALERT_ID, CHILD_ALERT_ID);
CREATE INDEX IDX_SUP_CHILD ON ALERT_SUPPRESSION(CHILD_ALERT_ID);
CREATE INDEX IDX_SUP_STATUS ON ALERT_SUPPRESSION(STATUS);

-- 3. 向 ALERT_RECORD 追加抑制相关字段
ALTER TABLE ALERT_RECORD ADD (
  SUPPRESSED_BY_ID  NUMBER,                        -- 抑制此告警的父告警 ID
  SUPPRESSED_AT     TIMESTAMP,                     -- 被抑制的时间
  SUPPRESSION_RULE  VARCHAR2(128)                  -- 命中的抑制规则名
);
COMMENT ON COLUMN ALERT_RECORD.SUPPRESSED_BY_ID IS '抑制此告警的父告警ID（F-17告警抑制）';

-- 4. 菜单项：告警抑制规则
MERGE INTO SYS_MENU t
USING (SELECT '/alerts/suppression' AS p FROM DUAL) s ON (t.MENU_PATH = s.p)
WHEN NOT MATCHED THEN INSERT (MENU_PATH, MENU_NAME, SORT_ORDER) VALUES ('/alerts/suppression', '告警抑制规则', 22);

-- 5. 授权 ADMIN/DBA/OPS
INSERT INTO SYS_ROLE_MENU (ROLE_ID, MENU_ID)
SELECT r.ROLE_ID, m.MENU_ID
FROM SYS_ROLE r, SYS_MENU m
WHERE r.ROLE_CODE IN ('ADMIN', 'DBA', 'OPS') AND m.MENU_PATH = '/alerts/suppression'
  AND NOT EXISTS (SELECT 1 FROM SYS_ROLE_MENU rm WHERE rm.ROLE_ID = r.ROLE_ID AND rm.MENU_ID = m.MENU_ID);

-- 6. 预置默认抑制规则
-- 规则1：拓扑级联 — 主机告警抑制该主机上所有实例告警
INSERT INTO ALERT_SUPPRESSION_RULE (RULE_NAME, RULE_TYPE, DESCRIPTION, PARENT_LEVELS, CHILD_LEVELS, SUPPRESS_WINDOW, CREATED_BY)
VALUES ('主机宕机抑制实例告警', 'TOPOLOGY', '主机级别的告警自动抑制该主机上所有数据库实例的告警', 'P1,P2', 'P2,P3,P4', 120, 'SYSTEM');

-- 规则2：拓扑级联 — 数据库实例告警抑制依赖该实例的应用告警
INSERT INTO ALERT_SUPPRESSION_RULE (RULE_NAME, RULE_TYPE, DESCRIPTION, PARENT_LEVELS, CHILD_LEVELS, SUPPRESS_WINDOW, CREATED_BY)
VALUES ('实例宕机抑制应用告警', 'TOPOLOGY', '数据库实例告警自动抑制依赖该实例的所有应用告警', 'P1,P2', 'P2,P3,P4', 120, 'SYSTEM');

-- 规则3：集群抑制 — 集群主节点告警抑制备节点告警
INSERT INTO ALERT_SUPPRESSION_RULE (RULE_NAME, RULE_TYPE, DESCRIPTION, PARENT_LEVELS, CHILD_LEVELS, SUPPRESS_WINDOW, CREATED_BY)
VALUES ('集群主节点抑制备节点', 'CLUSTER', '集群主节点（PRIMARY）告警自动抑制同集群备节点（STANDBY）的告警', 'P1,P2', 'P2,P3,P4', 60, 'SYSTEM');

-- 规则4：级别抑制 — 同实例高级别告警抑制低级别告警
INSERT INTO ALERT_SUPPRESSION_RULE (RULE_NAME, RULE_TYPE, DESCRIPTION, PARENT_LEVELS, CHILD_LEVELS, SUPPRESS_WINDOW, CREATED_BY)
VALUES ('P1抑制同实例低级别', 'SEVERITY', '同实例 P1 级别告警自动抑制 P2/P3/P4 级别告警', 'P1', 'P2,P3,P4', 60, 'SYSTEM');

COMMIT;
