-- Migration: F-04 Application-Database Relationship (应用-数据库关系)
-- Creates CMDB_APP and CMDB_APP_DB_RELATION tables for dependency graph and blast radius analysis

-- 1. 应用/业务系统表
CREATE TABLE CMDB_APP (
  APP_ID        NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  APP_NAME      VARCHAR2(128) NOT NULL,
  APP_CODE      VARCHAR2(64),          -- 应用编码（英文）
  APP_TYPE      VARCHAR2(32) DEFAULT 'APP',  -- APP/SERVICE/MICROSERVICE/MIDDLEWARE/OTHER
  DESCRIPTION   VARCHAR2(512),
  BIZ_LINE      VARCHAR2(128),         -- 所属业务线
  OWNER         VARCHAR2(64),          -- 负责人
  STATUS        VARCHAR2(16) DEFAULT 'ACTIVE',  -- ACTIVE/INACTIVE/DEPRECATED
  TENANT_ID     NUMBER DEFAULT 1,
  CREATED_BY    VARCHAR2(64),
  CREATED_AT    TIMESTAMP DEFAULT SYSTIMESTAMP,
  UPDATED_AT    TIMESTAMP DEFAULT SYSTIMESTAMP
);
COMMENT ON TABLE CMDB_APP IS '应用/业务系统（用于应用-数据库依赖关系管理）';
CREATE UNIQUE INDEX IDX_CMDB_APP_CODE ON CMDB_APP(APP_CODE);

-- 2. 应用-数据库依赖关系表
CREATE TABLE CMDB_APP_DB_RELATION (
  RELATION_ID   NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  APP_ID        NUMBER NOT NULL,
  INSTANCE_ID   NUMBER NOT NULL,
  RELATION_TYPE VARCHAR2(32) DEFAULT 'DEPENDS_ON',  -- DEPENDS_ON/READS_FROM/WRITES_TO/BACKUP_FOR
  DEPENDENCY    VARCHAR2(32) DEFAULT 'STRONG',       -- STRONG/WEAK/OPTIONAL
  DESCRIPTION   VARCHAR2(256),
  TENANT_ID     NUMBER DEFAULT 1,
  CREATED_BY    VARCHAR2(64),
  CREATED_AT    TIMESTAMP DEFAULT SYSTIMESTAMP,
  CONSTRAINT FK_ADR_APP      FOREIGN KEY (APP_ID)      REFERENCES CMDB_APP(APP_ID) ON DELETE CASCADE,
  CONSTRAINT FK_ADR_INSTANCE FOREIGN KEY (INSTANCE_ID)  REFERENCES CMDB_INSTANCE(INSTANCE_ID)
);
COMMENT ON TABLE CMDB_APP_DB_RELATION IS '应用与数据库依赖关系（F-04 拓扑图与爆炸半径分析）';
CREATE UNIQUE INDEX IDX_ADR_APP_INST ON CMDB_APP_DB_RELATION(APP_ID, INSTANCE_ID);
CREATE INDEX IDX_ADR_INSTANCE ON CMDB_APP_DB_RELATION(INSTANCE_ID);

-- 3. 菜单项：应用依赖管理
MERGE INTO SYS_MENU t
USING (SELECT '/cmdb/app-relation' AS p FROM DUAL) s ON (t.MENU_PATH = s.p)
WHEN NOT MATCHED THEN INSERT (MENU_PATH, MENU_NAME, SORT_ORDER) VALUES ('/cmdb/app-relation', '应用依赖关系', 57);

-- 4. 授权 ADMIN/DBA/OPS
INSERT INTO SYS_ROLE_MENU (ROLE_ID, MENU_ID)
SELECT r.ROLE_ID, m.MENU_ID
FROM SYS_ROLE r, SYS_MENU m
WHERE r.ROLE_CODE IN ('ADMIN', 'DBA') AND m.MENU_PATH = '/cmdb/app-relation'
  AND NOT EXISTS (SELECT 1 FROM SYS_ROLE_MENU rm WHERE rm.ROLE_ID = r.ROLE_ID AND rm.MENU_ID = m.MENU_ID);

INSERT INTO SYS_ROLE_MENU (ROLE_ID, MENU_ID)
SELECT r.ROLE_ID, m.MENU_ID
FROM SYS_ROLE r, SYS_MENU m
WHERE r.ROLE_CODE = 'OPS' AND m.MENU_PATH = '/cmdb/app-relation'
  AND NOT EXISTS (SELECT 1 FROM SYS_ROLE_MENU rm WHERE rm.ROLE_ID = r.ROLE_ID AND rm.MENU_ID = m.MENU_ID);

COMMIT;
