-- Migration: F-05 Tag Grouping System (标签与分组体系)
-- Creates CMDB_TAG_GROUP, CMDB_TAG, CMDB_INSTANCE_TAG tables
-- Supports: business line / environment / layer / level tags with batch operations

-- 1. 标签分组表（业务线、环境、层级、等级等维度）
CREATE TABLE CMDB_TAG_GROUP (
  GROUP_ID      NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  GROUP_NAME    VARCHAR2(64)  NOT NULL,          -- 分组名称（如：业务线、环境、层级、等级）
  GROUP_CODE    VARCHAR2(32)  NOT NULL,          -- 分组编码（如：BIZ_LINE、ENV、LAYER、LEVEL）
  DESCRIPTION   VARCHAR2(256),
  SORT_ORDER    NUMBER DEFAULT 0,
  STATUS        VARCHAR2(16)  DEFAULT 'ACTIVE',  -- ACTIVE / INACTIVE
  TENANT_ID     NUMBER DEFAULT 1,
  CREATED_AT    TIMESTAMP DEFAULT SYSTIMESTAMP,
  UPDATED_AT    TIMESTAMP DEFAULT SYSTIMESTAMP
);
COMMENT ON TABLE CMDB_TAG_GROUP IS '标签分组（业务线/环境/层级/等级等维度）';
CREATE UNIQUE INDEX IDX_TAG_GROUP_CODE ON CMDB_TAG_GROUP(GROUP_CODE);

-- 2. 标签表（具体的标签值）
CREATE TABLE CMDB_TAG (
  TAG_ID        NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  GROUP_ID      NUMBER NOT NULL,                 -- 所属分组
  TAG_NAME      VARCHAR2(64)  NOT NULL,          -- 标签名称（如：核心业务、生产环境、应用层）
  TAG_VALUE     VARCHAR2(128),                   -- 标签值（可选，用于 key-value 模式）
  COLOR         VARCHAR2(16),                    -- 前端展示颜色（如：#1890ff）
  DESCRIPTION   VARCHAR2(256),
  SORT_ORDER    NUMBER DEFAULT 0,
  STATUS        VARCHAR2(16)  DEFAULT 'ACTIVE',
  TENANT_ID     NUMBER DEFAULT 1,
  CREATED_BY    VARCHAR2(64),
  CREATED_AT    TIMESTAMP DEFAULT SYSTIMESTAMP,
  UPDATED_AT    TIMESTAMP DEFAULT SYSTIMESTAMP,
  CONSTRAINT FK_TAG_GROUP FOREIGN KEY (GROUP_ID) REFERENCES CMDB_TAG_GROUP(GROUP_ID) ON DELETE CASCADE
);
COMMENT ON TABLE CMDB_TAG IS '标签（属于某个分组的具体标签值）';
CREATE UNIQUE INDEX IDX_TAG_GROUP_NAME ON CMDB_TAG(GROUP_ID, TAG_NAME);

-- 3. 实例-标签关联表（多对多）
CREATE TABLE CMDB_INSTANCE_TAG (
  ID            NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  INSTANCE_ID   NUMBER NOT NULL,
  TAG_ID        NUMBER NOT NULL,
  CREATED_BY    VARCHAR2(64),
  CREATED_AT    TIMESTAMP DEFAULT SYSTIMESTAMP,
  CONSTRAINT FK_IT_INSTANCE FOREIGN KEY (INSTANCE_ID) REFERENCES CMDB_INSTANCE(INSTANCE_ID) ON DELETE CASCADE,
  CONSTRAINT FK_IT_TAG      FOREIGN KEY (TAG_ID)      REFERENCES CMDB_TAG(TAG_ID) ON DELETE CASCADE
);
COMMENT ON TABLE CMDB_INSTANCE_TAG IS '实例与标签的关联关系（多对多）';
CREATE UNIQUE INDEX IDX_IT_INST_TAG ON CMDB_INSTANCE_TAG(INSTANCE_ID, TAG_ID);
CREATE INDEX IDX_IT_TAG ON CMDB_INSTANCE_TAG(TAG_ID);

-- 4. 菜单项：标签管理
MERGE INTO SYS_MENU t
USING (SELECT '/cmdb/tags' AS p FROM DUAL) s ON (t.MENU_PATH = s.p)
WHEN NOT MATCHED THEN INSERT (MENU_PATH, MENU_NAME, SORT_ORDER) VALUES ('/cmdb/tags', '标签管理', 58);

-- 5. 授权 ADMIN/DBA/OPS
INSERT INTO SYS_ROLE_MENU (ROLE_ID, MENU_ID)
SELECT r.ROLE_ID, m.MENU_ID
FROM SYS_ROLE r, SYS_MENU m
WHERE r.ROLE_CODE IN ('ADMIN', 'DBA', 'OPS') AND m.MENU_PATH = '/cmdb/tags'
  AND NOT EXISTS (SELECT 1 FROM SYS_ROLE_MENU rm WHERE rm.ROLE_ID = r.ROLE_ID AND rm.MENU_ID = m.MENU_ID);

-- 6. 预置默认分组
INSERT INTO CMDB_TAG_GROUP (GROUP_NAME, GROUP_CODE, DESCRIPTION, SORT_ORDER) VALUES ('业务线', 'BIZ_LINE', '业务线分类', 1);
INSERT INTO CMDB_TAG_GROUP (GROUP_NAME, GROUP_CODE, DESCRIPTION, SORT_ORDER) VALUES ('环境', 'ENV', '部署环境', 2);
INSERT INTO CMDB_TAG_GROUP (GROUP_NAME, GROUP_CODE, DESCRIPTION, SORT_ORDER) VALUES ('层级', 'LAYER', '架构层级（应用层/中间件层/数据库层等）', 3);
INSERT INTO CMDB_TAG_GROUP (GROUP_NAME, GROUP_CODE, DESCRIPTION, SORT_ORDER) VALUES ('等级', 'LEVEL', '重要等级（核心/重要/一般等）', 4);
INSERT INTO CMDB_TAG_GROUP (GROUP_NAME, GROUP_CODE, DESCRIPTION, SORT_ORDER) VALUES ('自定义', 'CUSTOM', '自定义标签', 99);

-- 7. 预置默认标签
-- 业务线
INSERT INTO CMDB_TAG (GROUP_ID, TAG_NAME, COLOR, SORT_ORDER) SELECT GROUP_ID, '核心业务', '#f5222d', 1 FROM CMDB_TAG_GROUP WHERE GROUP_CODE='BIZ_LINE';
INSERT INTO CMDB_TAG (GROUP_ID, TAG_NAME, COLOR, SORT_ORDER) SELECT GROUP_ID, '营销系统', '#1890ff', 2 FROM CMDB_TAG_GROUP WHERE GROUP_CODE='BIZ_LINE';
INSERT INTO CMDB_TAG (GROUP_ID, TAG_NAME, COLOR, SORT_ORDER) SELECT GROUP_ID, '风控系统', '#faad14', 3 FROM CMDB_TAG_GROUP WHERE GROUP_CODE='BIZ_LINE';
INSERT INTO CMDB_TAG (GROUP_ID, TAG_NAME, COLOR, SORT_ORDER) SELECT GROUP_ID, '数据平台', '#52c41a', 4 FROM CMDB_TAG_GROUP WHERE GROUP_CODE='BIZ_LINE';
-- 环境
INSERT INTO CMDB_TAG (GROUP_ID, TAG_NAME, COLOR, SORT_ORDER) SELECT GROUP_ID, '生产环境', '#f5222d', 1 FROM CMDB_TAG_GROUP WHERE GROUP_CODE='ENV';
INSERT INTO CMDB_TAG (GROUP_ID, TAG_NAME, COLOR, SORT_ORDER) SELECT GROUP_ID, '预发布环境', '#fa8c16', 2 FROM CMDB_TAG_GROUP WHERE GROUP_CODE='ENV';
INSERT INTO CMDB_TAG (GROUP_ID, TAG_NAME, COLOR, SORT_ORDER) SELECT GROUP_ID, '测试环境', '#1890ff', 3 FROM CMDB_TAG_GROUP WHERE GROUP_CODE='ENV';
INSERT INTO CMDB_TAG (GROUP_ID, TAG_NAME, COLOR, SORT_ORDER) SELECT GROUP_ID, '开发环境', '#52c41a', 4 FROM CMDB_TAG_GROUP WHERE GROUP_CODE='ENV';
-- 层级
INSERT INTO CMDB_TAG (GROUP_ID, TAG_NAME, COLOR, SORT_ORDER) SELECT GROUP_ID, '应用层', '#1890ff', 1 FROM CMDB_TAG_GROUP WHERE GROUP_CODE='LAYER';
INSERT INTO CMDB_TAG (GROUP_ID, TAG_NAME, COLOR, SORT_ORDER) SELECT GROUP_ID, '中间件层', '#722ed1', 2 FROM CMDB_TAG_GROUP WHERE GROUP_CODE='LAYER';
INSERT INTO CMDB_TAG (GROUP_ID, TAG_NAME, COLOR, SORT_ORDER) SELECT GROUP_ID, '数据库层', '#13c2c2', 3 FROM CMDB_TAG_GROUP WHERE GROUP_CODE='LAYER';
INSERT INTO CMDB_TAG (GROUP_ID, TAG_NAME, COLOR, SORT_ORDER) SELECT GROUP_ID, '基础设施层', '#595959', 4 FROM CMDB_TAG_GROUP WHERE GROUP_CODE='LAYER';
-- 等级
INSERT INTO CMDB_TAG (GROUP_ID, TAG_NAME, COLOR, SORT_ORDER) SELECT GROUP_ID, '核心', '#f5222d', 1 FROM CMDB_TAG_GROUP WHERE GROUP_CODE='LEVEL';
INSERT INTO CMDB_TAG (GROUP_ID, TAG_NAME, COLOR, SORT_ORDER) SELECT GROUP_ID, '重要', '#fa8c16', 2 FROM CMDB_TAG_GROUP WHERE GROUP_CODE='LEVEL';
INSERT INTO CMDB_TAG (GROUP_ID, TAG_NAME, COLOR, SORT_ORDER) SELECT GROUP_ID, '一般', '#1890ff', 3 FROM CMDB_TAG_GROUP WHERE GROUP_CODE='LEVEL';

COMMIT;
