-- v1.4.1 ChatOps 历史按登录用户隔离：为 AI_CHAT_HISTORY 增加 CREATED_BY
-- 执行前请确认已执行 migration_v1_4_ai_analysis.sql

ALTER TABLE AI_CHAT_HISTORY ADD CREATED_BY VARCHAR2(64);
COMMENT ON COLUMN AI_CHAT_HISTORY.CREATED_BY IS '发起会话的登录用户名（智能问答历史隔离）';

CREATE INDEX IDX_AI_CHAT_USER_SESSION ON AI_CHAT_HISTORY(CREATED_BY, SESSION_ID, CREATED_AT DESC);
